= Ansible Container
:author: Antonio Costa
:email: antcosta@redhat.com
:docdate: 2022-04-18
:toc: left
:icons: font
:description: Container for running k8s-infra Ansible Playbooks

== Building the image

Place the current folder in the `container` subfolder.

[source, shell]
----
$ cd container
----

Launch the `buildah` image build using the `Dockerfile` file.

[source, shell]
----
$ buildah build-using-dockerfile --tag k8s-infra-ansible
----


== Before using the container

Using the container requires some information to be provided. The following information must be previously gathered.

* https://github.com/snowdrop/k8s-infra[k8s-infra] repository updated on the system
* https://github.com/snowdrop/pass[passwordstore] repository updated on the system
* GPG Keygrip ID and passphrase
* Git information

In this section the information is included as environment variables but a properties file can be created and provided as the source.

=== Getting the GPG Keygrip ID

First step before running the container is to identify the *Keygrip* ID of our own GPG key.

[source, shell]
----
$ gpg --list-secret-keys --with-keygrip
/home/johndoe/.gnupg/pubring.kbx
-------------------------------
sec   rsa2048 1970-01-01 [SC] [expires: 2099-12-31]
      KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      Keygrip = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
uid           [ultimate] Antonio Costa <johndoe@redhat.com>
ssb   rsa2048 1970-01-01 [SC] [expires: 2099-12-31]
      Keygrip = YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
----

The target key ID is the one identified in the `ssb` section.

With this information set 2 variables, `PASS_GPG_KEYGRIP_NAME` and `PASS_GPG_KEY_PASSPHRASE`. These 2 variables will be later passed to the container es environment variables.

[source, shell]
----
$ PASS_GPG_KEYGRIP_NAME=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
$ PASS_GPG_KEY_PASSPHRASE=mysupersecretandstrongpassphrase
----

=== Github information

Set the following variables for GIT.

* `GIT_EMAIL`
* `GIT_USERNAME`

=== Creating a properties file

The required information can be provided by using a properties file instead of independent environment variables.

Create the properties file, in this document the file will be `${HOME}/.k8s-infra-container.properties`.

[source, shell]
----
$ cat << EOF > ${HOME}/.k8s-infra-container.properties
GIT_EMAIL=johndoe@redhat.com
GIT_USERNAME=johndoe
PASS_GPG_KEYGRIP_NAME=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
EOF
----

CAUTION: Adding the gpg passphrase to the file might not be such a good idea.

CAUTION: Don't forget to change the file permissions to `U:R` only `chmod 600 ${HOME}/.k8s-infra-container.properties`.

== Running tasks inside the container

Connect to the container.

[source, shell]
----
$ podman run -it --rm -v /home/ajc102/docs/redhat/forks-github/k8s-infra:/opt/volumes/k8s-infra:Z -v /home/ajc102/docs/redhat/forks-github/pass/:/opt/volumes/pass:Z -v ${HOME}/.gnupg:/opt/volumes/gnupg:Z --env-file ${HOME}/.k8s-infra-container.properties -e PASS_GPG_KEY_PASSPHRASE=${PASS_GPG_KEY_PASSPHRASE} --entrypoint /bin/bash localhost/k8s-infra-ansible
----

Add the GitHub SSH key to the agent so the passphrase is not requested as part of the process execution.

[source, shell]
----
[root@9999999 ] exec ssh-agent $SHELL
[root@9999999 ] ssh-add ~/.ssh/id_ed25519_github
----

Execute the requested playbook.

[source, shell]
----
[root@9999999 ansible] VM_NAME=testcontainer-k121-centos8-test-04
[root@9999999 ansible] ansible-playbook playbook/openstack_vm_create_aggregate.yml -e vm_name=${VM_NAME}  -e k8s_type=masters -e k8s_version=121 -e '{"openstack": {"vm": {"network": "provider_net_shared" , "flavor": "ci.m5.large", "image": "CentOS-8-x86_64-GenericCloud-released-latest" }}}' --tags create
----


== Using the container

=== Requirements and preparation

[source, shell]
----
$ podman run --rm -v ${HOME}/docs/redhat/forks-github/k8s-infra:/opt/volumes/k8s-infra:Z -v ${PASSWORD_STORE_DIR}:/opt/volumes/pass:Z -v ${HOME}/.gnupg:/opt/volumes/gnupg:Z -e ANSIBLE_PLAYBOOK_FILE=playbook/ansible_test.yml localhost/k8s-infra-ansible
----

Create a VM.

[source, shell]
----
$ VM_NAME=k121-centos8-container-test
$ podman run --rm -v ${HOME}/docs/redhat/forks-github/k8s-infra:/opt/volumes/k8s-infra:Z -v ${PASSWORD_STORE_DIR}:/opt/volumes/pass:Z -v ${HOME}/.gnupg:/opt/volumes/gnupg:Z -v ${HOME}/.ssh:/root/.ssh:Z -e ANSIBLE_PLAYBOOK_FILE=playbook/openstack_vm_create_aggregate.yml -e ANSIBLE_PLAYBOOK_PARAMETERS="-e vm_name=${VM_NAME} -e k8s_type=masters -e k8s_version=121 -e '{\"openstack\": {\"vm\": {\"network\": \"provider_net_shared\" , \"flavor\": \"ci.m5.large\", \"image\": \"CentOS-8-x86_64-GenericCloud-released-latest\" }}}' --tags create" localhost/k8s-infra-ansible

VM_NAME=testcontainer-k121-centos8-test ; ansible-playbook playbook/openstack_vm_create_aggregate.yml -e vm_name=${VM_NAME}  -e k8s_type=masters -e k8s_version=121 -e '{"openstack": {"vm": {"network": "provider_net_shared" , "flavor": "ci.m5.large", "image": "CentOS-8-x86_64-GenericCloud-released-latest" }}}' --tags create
----

Remove VM.

[source, shell]
----
$ VM_NAME=k121-centos8-container-test
$ podman run --rm -v ${HOME}/docs/redhat/forks-github/k8s-infra:/opt/volumes/k8s-infra:Z -v ${PASSWORD_STORE_DIR}:/opt/volumes/pass:Z -v ${HOME}/.gnupg:/opt/volumes/gnupg:Z -v ${HOME}/.ssh:/root/.ssh:Z -e ANSIBLE_PLAYBOOK_FILE=playbook/openstack_vm_remove_aggregate.yml -e ANSIBLE_PLAYBOOK_PARAMETERS="-e vm_name=${VM_NAME}" localhost/k8s-infra-ansible
----


== Troubleshooting

=== GPG key, keygrip and passphrase

This section presents troubleshooting steps for setting the GPG passphrase.

Start the `gpg-agent` on the container. If it's already running it can be killed by using `gpgconf --kill gpg-agent`.

[source, shell]
----
$ gpg-agent --verbose --daemon --log-file /tmp/gpg-agent.log --allow-preset-passphrase --default-cache-ttl=31536000
----

List the known keys.

[source, shell]
----
$ gpg-connect-agent 'keyinfo --list' /bye
S KEYINFO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA D - - - P - - -
S KEYINFO BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB D - - - P - - -
S KEYINFO CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC D - - - P - - -
...
----

Add the passphrase.

[source, shell]
----
$ echo "${PASS_GPG_KEY_PASSPHRASE}" | /usr/libexec/gpg-preset-passphrase --verbose --preset ${PASS_GPG_KEYGRIP_NAME}
----

For the sake of the example the key is `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`. After setting the passphrase verify that the key information has been updated with a `1` on the key information.

[source, shell]
----
$ gpg-connect-agent 'keyinfo --list' /bye
S KEYINFO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA D - - 1 P - - -
S KEYINFO BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB D - - - P - - -
S KEYINFO CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC D - - - P - - -
...
----

After this the passwordstore should be usable without requesting the passphrase.

[source, shell]
----
$ pass insert x
Enter password for x: 
Retype password for x: 
[master 998232c] Add given password for x to store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 x.gpg
$ pass rm x
Are you sure you would like to delete x? [y/N] y
removed '/opt/volumes/pass/x.gpg'
[master 140fb7e] Remove x from store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 x.gpg
[root@e0e2d962be41 pass]#
----

