:icons: font
:revdate: {docdate}
:toc: macro
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= Automating the deployment of a kubernetes/ocp cluster

This project details the `prerequisites` and `steps` necessary to automate the installation of a Kubernetes (aka k8s) cluster or Openshift 4 top of one of the following cloud provider:

* Red Hat OpenStack (RHOS-PSI)
* Red Hat https://github.com/resource-hub-dev[ResourceHub] - Work in progress
* IBM Cloud
* Hetzner
* Kind**

NOTE: kind is not a cloud provider but a tool able to run a k8s cluster on a container engine

== Prerequisites

To use the scripts, playbooks, part of this project, some prerequisites are needed. It is not mandatory to install
all of them and the following chapters will mention which ones are needed.

* https://kind.sigs.k8s.io/docs/user/quick-start/#installation[kind]
* https://docs.docker.com/engine/install/[Docker] or https://podman.io/docs/installation[podman]
* https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-and-upgrading-ansible[Ansible]
* https://www.passwordstore.org/[passwordstore]

== Locally

The word `locally` should be understood as the process to run on your developer laptop the cluster, using also a CI/CD platform
such as GitHub Actions, etc.

We recommend to use 2 tools to run locally a kubernetes cluster: kind or minikube

=== Kind

_Tools: docker (or podman), kind_

To automate the installation of a k8s "kind" cluster locally like also to set up an ingress controller or a docker container registry,
use our opinionated xref:kind/README.adoc[bash scripts] we created :-).

You can find more information about kind tool using the official documentation - https://kind.sigs.k8s.io/docs/user/quick-start/

=== Minikube

_Tools: docker (or podman), minikube_

See the https://kubernetes.io/docs/tasks/tools/install-minikube/[official documentation] to install `minikube` on Macos, Linux or Windows

== Cloud provider

=== Red Hat

==== OpenStack - RHOS

_Tools: password store, ansible_

See xref:openstack/README.adoc[OpenStack] page explaining how to create an OpenStack cloud vm.

==== https://resourcehub.redhat.com/[Resource Hub]

_Tools: password store, ansible_

Work in progress

=== IBM Cloud

_Tools: password store, ansible_

See xref:ibm-cloud/README.adoc[ibm-cloud]

=== Hetzner - bare metal

_Tools: password store, ansible_

See xref:hetzner/README.adoc[hetzner] page explaining how to create a vm.

=== Hetzner Cloud - virtualized

_Tools: password store, ansible_

See xref:hetzner/README-cloud.adoc[hetzner-cloud] page explaining how to create a cloud vm.

== Cluster Deployment

As the vm is now running and the docker daemon is up, you can install your `k8s` distribution using either one of the following approaches :

=== Kubernetes

You can then use the following instructions to install a Kubernetes cluster with the help of Ansible and the xref:doc/k8s.adoc[roles we created]

=== OpenShift

* Simple using the `oc` binary tool and the command https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[oc cluster up] within the vm
* More elaborated using `Ansible` tool and one of the following playbook/role:
 ** `oc cluster up` xref:doc/oc.adoc[role]
 ** `openshift-ansible` all-in-one playbook as described xref:doc/cloud.adoc[here]

== Sandbox

xref:sandbox/sandbox.adoc[Material] not actively maintained to create a VM, run on your desktop a k8s cluster or provision it with Istio, Jaeger, Fabric8 launcher, Ansible Broker catalog, etc
