= How to easily manage a Kubernetes cluster using kind
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

The goal of this project is to simplify the life of the developers to manage a kubernetes
cluster with the following default features:

* Launch a container registry using the specified port `e.g. localhost:5000`,
* Set up an Ingress controller to route the external traffic to the cluster.

For that purpose, several bash scripts have been developed.

[NOTE]
====
These scripts can also be used directly from the https://github.com/snowdrop/k8s-infra/[snowdrop/k8s-infra GitHub repository] using `curl`. 

Example: `curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s ...`

`kind.sh` can be replaced by any of the other scripts included in this document.
====

=== Kind Cluster

To create or delete a cluster using the https://kind.sigs.k8s.io/[kind] use the https://github.com/snowdrop/k8s-infra/blob/main/kind/kind.sh[`kind.sh`] script.

=== Container Registry

To create or delete a container registry use the https://github.com/snowdrop/k8s-infra/blob/main/kind/kind.sh[`registry.sh`] script.

The container registry is started as a `container`, its network shared with the host and can be deployed using the mode:

* Unsecure: plain HTTP without user authentication (default)
* Secured: HTTP/TLS using https://httpd.apache.org/docs/current/programs/htpasswd.html[htpasswd] to authenticate the users

== Prerequisite

To be able to use the bash script, the following tools are required:

* A container runtime (one of):
** Podman: https://podman.io/
** Docker: https://docs.docker.com/get-docker/
* kind: https://github.com/kubernetes-sigs/kind/releases
* kubectl: https://kubernetes.io/docs/tasks/tools/
* helm: https://helm.sh/
* jq: https://stedolan.github.io/jq/download/
** Used for validating the environment
* openssl: 
** _optional_, unless a secure container registry is used

== Usage

Open a terminal and at the root of this repository, execute the following command:

[source,bash]
----
./kind/kind.sh command [parameters,...]
----

The available commands are:

.Script commands
[%header,cols="2m,4"]
|===
| Command | Description

| install | Create a "kind" kubernetes cluster
| remove | Remove the "kind" kubernetes cluster
|===

=== Relevant options

Other relevant parameters are the following.

.Script options
[%header,cols="2,4"]
|===
| Command | Description

| `--ingress`

[.fuchsia]#string# 
a| Ingress controller to be deployed.

Choices: 

* `kourier`
* *`nginx`` <= Default*

| `--cluster-name`

[.fuchsia]#string#
a| Name of the cluster.

Default: kind

| `--port-map`

[.fuchsia]#string#
a| Comma separated list of extra ports mappings. See https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings[kind config].

_e.g._: `ContainerPort1:HostPort1,...`

[WARNING]
====
The ports required to be accessed from outside the kind cluster 
must be mapped between the host and the kind container using this 
parameter.
====

| `--provider`

[.fuchsia]#string#
a| Allows selecting the container runtime to be used. 

Choices: 

* *`docker` <= Default*
* `podman` (see: https://kind.sigs.k8s.io/docs/user/rootless/#creating-a-kind-cluster-with-rootless-podman[kind rootless podman doc])

|===


== Install

This script allows creating both a kind cluster with associated ingress controller and a container registry in separate commands.

=== Container Registry

The first (optional) step is creating a container registry.

.Container Registry creation most relevant options
[%header,cols="2,4"]
|===
| parameter | Description

| `--registry-name`

[.fuchsia]#string# 
a| Name to be given to the registry.

Default: kind-registry

| `--registry-password`

[.fuchsia]#string# 
a| Registry user password.

Default: `snowdrop`

| `--registry-port`

[.fuchsia]#string#
a| Port to be assigned to the Container Registry.

Default: 5000

| `--registry-user`

[.fuchsia]#string#
a| Registry user.

Default: `admin`
|===

.Container registry creation statement
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install-registry --registry-name kind-registry.local
----

=== Kind Cluster

Creating a kubernetes cluster is as simple as executing the following command.

.kind deploy statement
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install-cluster --cluster-name snowdrop --provider podman --port-map "30000:30000,31000:31000 --registry-name kind-registry.local"
----

.kind cluster creation most relevant options
[%header,cols="2,4"]
|===
| parameter | Description

| `--registry-name`

[.fuchsia]#string# 
a| Name of the registry to use.

Default: kind-registry

| `--registry-port`

[.fuchsia]#string#
a| Port to be assigned to the Container Registry.

Default: 5000
|===

=== Post deployment steps

==== Allow using an insecure container registry

*Using Podman*

Check the link:https://podman.io/getting-started/installation.html[Podman installation]
 document.

.Instructions for Podman
[%collapsible]
====
Add the `kind-registry.conf` file to the `/etc/containers/registries.conf.d/` folder having the following contents.

.Allow using the newly created insecure registry 
[source]
----
[[registry]]
location = "localhost:5000"
insecure = true
----
====

*Using Docker*

Check the link:https://docs.docker.com/registry/insecure/[Test an insecure registry] 
Docker document.

.Instructions for Docker
[%collapsible]
====
Add the following contents to the `/etc/docker/daemon.json` file.

[source,json]
----
{
  "insecure-registries" : ["localhost:5000"]
}
----

====

== Remove

To undeploying a previousy deployed kind cluster use the `remove` action on the kind deploy script.

.kind undeploy statement
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s remove --cluster-name snowdrop
----

== Secured docker registry

To deploy a local secured (using htpasswd) docker registry use the `--secure-registry` parameter.

The security related parameters are the following.

.Security related parameters
[%header,cols="2,5"]
|===
| Command | Description

| `--secure-registry`
| Secure the docker registry.

| `--registry-user`

[.fuchsia]#string#
a| Registry user.

*Default: `admin`*

| `--registry-password`

[.fuchsia]#string#
a| Registry user password.

*Default: `snowdrop`*

|===


When the cluster is created, add to your `/etc/hosts` file a new entry
to map the `localhost ip` address with the name of the registry

....
::1 
127.0.0.1 kind-registry kind-registry
....

The certificate generated is available at `~/.registry/certs/<CLUSTER_NAME>-registry`

You can log on to the registry using the user and password as defined previously.

[source,bash]
----
docker login -u admin -p snowdrop kind-registry:5000
----

*REMARK*: If needed by the tools such as podman, crt, crictl, … move the
file of the certificate under by example
`/etc/docker/certs.d/kind-registry:5000/client.cert`

== How to check

=== Container registry

To verify if you can use the (secured) container registry, then execute the following commands:
[source,bash]
----
docker pull gcr.io/google-samples/hello-app:1.0
docker tag gcr.io/google-samples/hello-app:1.0 kind-registry:5000/google-samples/hello-app:1.0

docker logout kind-registry:5000
docker login kind-registry:5000 -u admin -p snowdrop
docker push kind-registry:5000/google-samples/hello-app:1.0

kubectl delete secret regcred
kubectl create secret docker-registry regcred --docker-server=kind-registry:5000 --docker-username=admin --docker-password=snowdrop
kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}'
kubectl delete deployment hello
kubectl create deployment hello --image=kind-registry:5000/google-samples/hello-app:1.0

kubectl get pod -lapp=hello
NAME                     READY   STATUS    RESTARTS   AGE
hello-7689699f4b-mbrr2   1/1     Running   0          21s
----

=== Ingress controller

To verify if the ingress route is working, use the following example
part of the
https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress[kind]
documentation like
https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry[this
page] too to tag/push a container image to the `localhost:5000` registry

'''''

*1*: The kubernetes `default version` depends on the version of the kind
tool installed (e.g. 1.20.2 corresponds to kind 0.10.0). See the release
note to find such information like the list of the
https://github.com/kubernetes-sigs/kind/releases[supported images]. The
list of the `kind - kubernetes` images and their version (1.14.x,
1.15.y,…) can be consulted
https://registry.hub.docker.com/v1/repositories/kindest/node/tags[here]

== Multiple Clusters

The kind bash script now supports deploying multiple cluster. Simply 
execute the script passing as para meter a new cluster name and

.Get list of clusters from kubeconfig
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install-cluster --cluster-name snowdrop2 --registry-name kind-registry.local --ingress-ports '10080:10443'
----

[WARNING]
====
Check the `--ingress-ports` to make sure there are no conflicts with 
the ports of the different ingress controlers of each cluster.
Each set of ports must be happed with the host ports.
====

Check the list of clusters defined in the kube configuration file.

.Get list of clusters from kubeconfig
[source,bash]
----
kubectl config get-clusters
----

As a result the different clusters will be shown.

.Cluster list with multiple clusters
[source,]
----
NAME
snowdrop2
snowdrop
----
