= How to create a Kubernetes cluster locally
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 2

== Introduction

The goal of this project is to simplify our life when we use kubernetes
on a laptop. It currently supports the following features: 

* Create/delete a K8s cluster using the latest cluster version, or the one you specify, 
* Launch a local container registry exposed on port `localhost:5000`, 
* Set up an Ingress controller to route the traffic. 

The bash script has been developed supporting the installation of a container registry according to the following options: 

* Unsecure: plain HTTP
* Secured: HTTP/HTTPS endpoints available and authentication using https://httpd.apache.org/docs/current/programs/htpasswd.html[htpasswd]

== Prerequisite

To be able to create a kubernetes cluster using this project, the following tools are required:

* A container runtime:
** Podman: https://podman.io/
** Docker: https://docs.docker.com/get-docker/
* Kind: https://github.com/kubernetes-sigs/kind/releases
* kubectl: https://kubernetes.io/docs/tasks/tools/
* helm: https://helm.sh/
* jq: https://stedolan.github.io/jq/download/ (optional)
* openssl (optional)

== Usage

Open a terminal and at the root of this repository, execute the following command:

[source,bash]
----
./kind/kind.sh command [parameters,...]
----

The available commands are:

.Script commands
[%header,cols="2m,4"]
|===
| Command | Description

| install | Create a "kind" kubernetes cluster
| remove | Remove the "kind" kubernetes cluster
|===

=== Relevant options

Other relevant parameters are the following.

.Script commands
[%header,cols="2,5"]
|===
| Command | Description

| `--ingress`

[.fuchsia]#string# 
a| Ingress controller to be deployed.

Choices: 

* `kourier`
* *`nginx`` <= Default*

| `--cluster-name`

[.fuchsia]#string#
a| Name of the cluster.

Default: kind

| `--port-map`

[.fuchsia]#string#
a| Comma separated list of ports to map on kind config.

_e.g._: `ContainerPort1:HostPort1,...`

[WARNING]
====
The ports required to be accessed from outside the kind cluster must be mapped between the host and the kind container using this parameter.
====

| `--provider`

[.fuchsia]#string#
a| Allows selecting the container runtime to be used. 

Choices: 

* *`docker` <= Default*
* `podman`

|===


== Install

Creating a kubernetes cluster is as simple as executing the following command.

.kind deploy statement
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install --cluster-name snowdrop --provider podman --port-map "30000:30000,31000:31000"
----

=== Post deployment steps

==== Allow using an insecure container registry

*Using Podman*

Check the link:https://podman.io/getting-started/installation.html[Podman installation]
 document.

.Instructions for Podman
[%collapsible]
====
Add the `kind-registry.conf` file to the `/etc/containers/registries.conf.d/` folder having the following contents.

.Allow using the newly created insecure registry 
[source]
----
[[registry]]
location = "localhost:5000"
insecure = true
----
====

*Using Docker*

Check the link:https://docs.docker.com/registry/insecure/[Test an insecure registry
]
Docker document.

.Instructions for Docker
[%collapsible]
====
Add the following contents to the `/etc/docker/daemon.json` file.

[source,json]
----
{
  "insecure-registries" : ["localhost:5000"]
}
----

====

== Remove

To undeploying a previousy deployed kind cluster use the `remove` action on the kind deploy script.

.kind undeploy statement
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s remove --cluster-name snowdrop
----

== Secured docker registry

To deploy a local secured (using htpasswd) docker registry use the `--secure-registry` parameter.

The security related parameters are the following.

.Security related parameters
[%header,cols="2,5"]
|===
| Command | Description

| `--secure-registry`
| Secure the docker registry.

| `--registry-user`

[.fuchsia]#string#
a| Registry user.

*Default: `admin`*

| `--registry-password`

[.fuchsia]#string#
a| Registry user password.

*Default: `snowdrop`*

|===


When the cluster is created, add to your `/etc/hosts` file a new entry
to map the `localhost ip` address with the name of the registry

....
::1 
127.0.0.1 registry.local kind-registry
....

The certificate generated is available at `$HOME/local-registry.crt`

You can log on to the registry using the user and password as defined previously.

[source,bash]
----
docker login -u admin -p snowdrop registry.local:5000
----

*REMARK*: If needed by the tools such as podman, crt, crictl, … move the
file of the certificate under by example
`/etc/docker/certs.d/kind-registry:5000/client.cert`

=== How to check

To verify if the ingress route is working, use the following example
part of the
https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress[kind]
documentation like
https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry[this
page] too to tag/push a container image to the `localhost:5000` registry

'''''

*1*: The kubernetes `default version` depends on the version of the kind
tool installed (e.g. 1.20.2 corresponds to kind 0.10.0). See the release
note to find such information like the list of the
https://github.com/kubernetes-sigs/kind/releases[supported images]. The
list of the `kind - kubernetes` images and their version (1.14.x,
1.15.y,…) can be consulted
https://registry.hub.docker.com/v1/repositories/kindest/node/tags[here]
