= OCP Ansible Playbooks
:icons: font
:toc: left
:description: This document describes OCP specific playbooks.

== Before you start

[IMPORTANT]
====
The Ansible commands should be executed within the ansible folder !
====

== OCP On OpenStack

Playbooks to deploy and remove an OCP cluster to RHOS.

.List of OCP RHOS playbooks
[cols="2m,1m,5"]
|===
|Playbook File |Description

| ocp_openstack_install.yml
| Deploy an OCP cluster on RHOS.

| ocp_openstack_remove.yml
| Remove an OCP cluster on RHOS.

| ocp_openstack_info.yml
| Print information from the OCP cluster, for dev/testing purposes.

| ocp_openstack_test.yml
| Test some functionalities, for dev/testing purposes only!
|===

// tag::deploy_ocp_on_rhos[]
=== Deploy OCP Cluster on RHOS

First obtain the OCP pull secret which can be obained from https://console.redhat.com/openshift/install/pull-secret.

Execute the playbook.

.Command to execute the OCP deployment playbook.
[source,bash]
----
ansible-playbook -i inventory/ playbook/ocp/ocp_openstack_install.yml -e work_directory=/opt/ocp -e openshift_pull_secret=${OCP_PULL_SECRET} -K
----

The playbook will result on the deployment of several RHOS VMs for control plane and worker nodes.

.Note on the RHOS VM flavors
[NOTE]
====
The RHOS flavors to be used on the VMs that will result on the OCP cluster are
defined by the `openstack_flavor_control_plane` and `openstack_flavor_compute` 
variables, having as default the values from the role defaults file.

.Ansible Role default flavor configuration
[source,yaml]
----
include::../../roles/ocp_cluster/defaults/main.yml[tag=rhos_default_flavors]
----

The list of flavors is identified on the link:../../../openstack/README.adoc#Flavors[OpenStack README file].
====
// end::deploy_ocp_on_rhos[]

// tag::undeploy_ocp_on_rhos[]
=== Undeploy OCP Cluster on RHOS

[WARNING]
====
For the removal process to be successfull the OCP installation directory 
(`installation_dir`) must be provided as it store information on the RHOS
objects associated to the project.
====

.Command to execute the OCP cluster removal playbook.
[source,bash]
----
ansible-playbook -i inventory/ playbook/ocp/ocp_openstack_remove.yml \
  -e work_directory=/opt/ocp \
  -e installation_dir=/opt/ocp/openshift-data/
----
// end::undeploy_ocp_on_rhos[]

=== Other OCP RHOS Playbooks

[source,bash]
----
ansible-playbook playbook/ocp/ocp_openstack_info.yml -e work_directory=/opt/ocp -e installation_dir=/opt/ocp/openshift-data/ -e ocp_cluster_name=ocp -e snowdrop_domain="snowdrop.dev"  -vv
----

== Playbooks

=== PasswordStore

Create OpenStack instance based on passwordstore

.openstack_vm_create_paswordstore parameters
[cols="2m,1m,5"]
|===
|Field name |Mandatory |Description

| vm_name
| x
| Name of the VM being created. Will be used both as hostname as well as Ansible Inventory name.

| openstack.vm.network
| x
| Value for the OpenStack provider network. `provider_net_shared`

| openstack.vm.image
| x
| OpenStack VM image, e.g. `Fedora-Cloud-Base-35`.

| openstack.vm.flavor"
| x
| OpenStack VM flavor (size), e.g. `m1.medium`.

| key_name
| -
| Use an existing SSH key (value) instead of creating one for the VM.

| k8s_type
| *for k8s hosts.*
| Kubernetes host type [master,worker].

| k8s_version
| *for k8s hosts.*
| Kubernetes version to be associated with the host, e.g. for version `1.23` use `123`. This is actually an Ansible Inventory group having definitions associated with each of the Kubernetes version.
|===

[source,bash]
----
$ VM_NAME=vm20210221-t01
----

[source,bash]
----
$ ansible-playbook playbook/openstack/openstack_vm_create_paswordstore.yml -e k8s_type=masters -e k8s_version=123 -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-35", "flavor": "m1.medium"}}}' -e key_name=test-adm-key -e vm_name=${VM_NAME} 
----

This playbook should finish with something like:

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=68   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
vm20210221-t01             : ok=32   changed=20   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

Monday 21 February 2022  13:01:53 +0100 (0:00:05.011)       0:12:51.042 ******* 
=============================================================================== 
openstack/init_vm : Upgrade all packages ------------------------------------------------- 305.39s
openstack/vm : Create VM instance -------------------------------------------------------- 121.94s
sec/firewalld : Install firewalld --------------------------------------------------------- 47.60s
openstack/init_vm : Install packages ------------------------------------------------------ 47.22s
openstack/init_vm : Reboot instance ------------------------------------------------------- 32.76s
Refresh the inventory so the newly added host is available -------------------------------- 21.10s
sec/sshd_port : Change SELINUX settings to allow connections to the new port --------------- 9.14s
sec/motd : Config | Install custom `/etc/motd` file ---------------------------------------- 8.24s
sec/audit : Apply auditd configuration ----------------------------------------------------- 8.06s
openstack/vm : Gather information about a previously created image with same name ---------- 7.85s
Wait for connection to host ---------------------------------------------------------------- 7.02s
openstack/vm : Wait for boot --------------------------------------------------------------- 6.55s
Gathering Facts ---------------------------------------------------------------------------- 5.77s
sec/firewalld : Enable and start firewalld ------------------------------------------------- 5.53s
Gathering Facts ---------------------------------------------------------------------------- 5.08s
sec/update : Update all packages ----------------------------------------------------------- 5.01s
sec/firewalld : firewalld - Manage firewall ports ------------------------------------------ 4.96s
sec/sshd_port : Change the ssh port number ------------------------------------------------- 4.60s
sec/firewalld : firewalld - Manage firewall services --------------------------------------- 4.58s
sec/firewalld : Restart firewalld ---------------------------------------------------------- 4.51s
....

The playbook also uses the variables defined in `roles/openstack/vm/defaults/main.yml`. Those variables can also be overridden using the syntax above.

[source,yaml]
----
include::../../roles/openstack/vm/defaults/main.yml[]
----

=== Delete a VM

To delete a VM, simply execute the `openstack_vm_remove_aggregate` playbook.

[source,bash]
----
ansible-playbook -i inventory/ playbook/ocp/ocp_openstack_install.yml -e target_dir=/home/ajc102/docs/redhat/_tmp/ocp
----

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2   

Monday 21 February 2022  13:07:58 +0100 (0:00:02.485)       0:00:30.900 ******* 
=============================================================================== 
openstack/vm : Gather information about a previously created image named  ------------------ 8.16s
openstack/vm : Delete  --------------------------------------------------------------------- 3.91s
openstack/vm : Delete VM volume ------------------------------------------------------------ 3.41s
openstack/vm : Delete key  from server ----------------------------------------------------- 2.93s
Push changes to the pass git database ------------------------------------------------------ 2.49s
Pull pass git database --------------------------------------------------------------------- 2.16s
openstack/vm : Set pass facts from passwordstore ------------------------------------------- 1.70s
openstack/vm : Remove existing SSH key to use with instance -------------------------------- 1.55s
openstack/vm : Find admin user home folder ------------------------------------------------- 0.98s
openstack/vm : Remove the host from the known_hosts file ----------------------------------- 0.95s
openstack/vm : stat ------------------------------------------------------------------------ 0.88s
Remove passstore entries ------------------------------------------------------------------- 0.74s
Remove local ssh keys ---------------------------------------------------------------------- 0.57s
openstack/vm : include_tasks --------------------------------------------------------------- 0.14s
Validate required variables ---------------------------------------------------------------- 0.08s
openstack/vm : Print Openstack output ------------------------------------------------------ 0.07s
openstack/vm : include_tasks --------------------------------------------------------------- 0.07s
....

=== Connect to the new instance

Since all the information related to the host will be managed by our ansible passwordstore roles, which also stores the ssh public and secret keys locally on the `~/.ssh` folder, to login to the newly created VM is as simple as launching the following command.

[source,bash]
----
$ ssh -i ~/.ssh/id_rsa_snowdrop_openstack_${VM_NAME} `pass show openstack/${VM_NAME}/os_user | head -n 1`@`pass show openstack/${VM_NAME}/ansible_ssh_host | head -n 1` -p `pass show openstack/${VM_NAME}/ansible_ssh_port | head -n 1`
----

This should connect ot the newly created VM.

[source]
====
Last login: Thu Jan 1 00:00:00 1970 from x.x.x.x
------------------

This machine is property of RedHat.
Access is forbidden to all unauthorized person.
All activity is being monitored.

Welcome to vm20210221-t01..
====

