= OpenStack Ansible Playbooks
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:toc: left
:description: This document describes OpenStack specific playbooks.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Before you start

=== Choose an image

NOTE: The list of images is identified on the link:../../../openstack/README.adoc#Images[OpenStack README file].

Different OS images are available on Openstack. To select a specific image use the `openstack.vm.image` variable override.

=== Choose a flavor

NOTE: The list of flavors is identified on the link:../../../openstack/README.adoc#Flavors[OpenStack README file].

== Playbooks

=== Create a VM with Passwordstore

Create an OpenStack instance (aka a VM) using link:../../../passwordstore/README.adoc[passwordstore] as tools to manage the credentials, information.

[NOTE]
====
The playbook also uses the variables defined in the link:https://github.com/snowdrop/ansible-collection-cloud-infra/blob/main/roles/openstack_vm/defaults/main.yml[`openstack/vm role of the Snowdrop Cloud Infra Ansible Collection`] 
 that can also be overridden.
====

.OpenStack VM Create Passwordstore parameters
[cols="20%,80%"]
|===
|Field name | Description

| `default_generic_key_name`

[.fuchsia]#string#

a| Generic key name

| `openstack.vm`

[.fuchsia]#map#

[.red]#required# 

a| Map with required attributes for RHOS.

Check the <<openstack-vm-map-param-table>> table below for more details.

| `rhos_auth_type`

[.fuchsia]#string#

a| RHOSP Authentication type

Check the `openstack` CLI man page (`man openstack`) for available types, or 
 our link:../../../openstack/README.adoc#rhosp-authentication[Red Hat Open Stack document].

* *`v3password` <= Default*
* ...

| `vm_name`

[.fuchsia]#string#

[.red]#required# 

a| Name of the VM being created. 

This name will be used both as hostname as well as Ansible Inventory name.

|===

[#openstack-vm-map-param-table,reftext="`openstack.vm` parameter map"]
.openstack.vm map parameter
[cols="20%,80%"]
|===
|Field name | Description

| `flavor`

[.fuchsia]#string#

[.red]#required# 

a| RHOS Flavor specifying the CPU, RAM and DISK sizes.

| `image`

[.fuchsia]#string#

[.red]#required# 

a| OS Image to be used (e.g. `Fedora-Cloud-Base-37`).

| `network`

[.fuchsia]#string#

[.red]#required# 

a| Network provider in RHOS

|===

To create the RHOSP launch the `openstack_vm_create_passwordstore.yml` Ansible Playbook 
 using the following command.

[source,bash]
----
ansible-playbook playbook/openstack/openstack_vm_create_passwordstore.yml -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-37", "flavor": "m1.medium"}}}' -e vm_name=snowdrop_sample_vm_name
----

[NOTE]
====
Some error messages might show on the installation process and be ignored by the installation process. Nevertheless the playbook should finish with no failed tasks.
====

This is a sample result of the playbook execution.

[source]
----
PLAY RECAP *******************************************************************************************************
localhost                  : ok=68   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
vm20210221-t01             : ok=32   changed=20   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
----

After creating the VM this playbook also executes the VM secure host playbook. This is an independent playbook that can be executed against any host. More information link:../README.adoc#secure-host[here].

Besides creating the VM the playbook also performs the following operations:

* Store the host SSH keys on the controller device.
* Add entries to the known hosts file for this host.
* Add several entries to the passwordstore database in order to build the Ansible Inventory

=== Delete a VM with Passwordstore

To delete a VM, simply execute the `openstack_vm_remove_aggregate` playbook. Besides 
 removing the VM from the RHOSP it will also remove the entries from the passwordstore 
 database as well as any VM local ssh keys and entries from known hosts.

[source,bash]
----
ansible-playbook ansible/playbook/openstack/openstack_vm_remove_passwordstore.yml -e vm_name=snowdrop_sample_vm_name
----

Although some failures might occur some might be ignored which shouldn't affect thhe process. This playbook should finish with no failed tasks.

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2   

....

