= OpenStack Ansible Playbooks
Snowdrop Team (Antonio Costa)
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:revdate: {docdate}
:toc: left
:description: This document describes OpenStack specific playbooks.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Before you start

=== Choose an image

NOTE: The list of images is identified on the link:../../../openstack/README.adoc#Images[OpenStack README file].

Different OS images are available on Openstack. To select a specific image use the `openstack.vm.image` variable override.

=== Choose a flavor

NOTE: The list of flavors is identified on the link:../../../openstack/README.adoc#Flavors[OpenStack README file].

== Playbooks

=== Create a VM

Create OpenStack instance based on passwordstore.

.openstack_vm_create_passwordstore parameters
[cols="20%,80%"]
|===
|Field name | Description

| `vm_name`

[.fuchsia]#string#

[.red]#required# 

a| Name of the VM being created. 

This name will be used both as hostname as well as Ansible Inventory name.

| `openstack.vm`

[.fuchsia]#map#

[.red]#required# 

a| Map with required attributes for RHOS.

Check below for more details.

|===

.openstack.vm map parameter
[cols="20%,80%"]
|===
|Field name | Description

| `flavor`

[.fuchsia]#string#

[.red]#required# 

a| RHOS Flavor specifying the CPU, RAM and DISK sizes.

| `image`

[.fuchsia]#string#

[.red]#required# 

a| OS Image to be used (e.g. `Fedora-Cloud-Base-37`).

| `network`

[.fuchsia]#string#

[.red]#required# 

a| Network provider in RHOS

|===

[source,bash]
----
$ VM_NAME=vm20210221-t01
----

[source,bash]
----
$ ansible-playbook playbook/openstack/openstack_vm_create_passwordstore.yml -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-35", "flavor": "m1.medium"}}}' -e key_name=test-adm-key -e vm_name=${VM_NAME} 
----

Although some failures might occur some might be ignored which shouldn't affect thhe process. This playbook should finish with no failed tasks.

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=68   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
vm20210221-t01             : ok=32   changed=20   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

....

The playbook also uses the variables defined in `roles/openstack/vm/defaults/main.yml`. Those variables can also be overridden using the syntax above.

=== Delete a VM

To delete a VM, simply execute the `openstack_vm_remove_aggregate` playbook.

[source,bash]
----
$ ansible-playbook ansible/playbook/openstack/openstack_vm_remove_passwordstore.yml -e vm_name=${VM_NAME}
----

Although some failures might occur some might be ignored which shouldn't affect thhe process. This playbook should finish with no failed tasks.

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2   

....

=== Connect to the new instance

All the information related to the host will be managed by our ansible passwordstore link:../../roles/passstore[roles] and link:../passstore[playbooks]. The current implementation also stores the ssh public and secret keys locally on each `~/.ssh` folder. To improve usability link:../../../tools/passstore-vm-ssh.sh[this] bash script has been created to make it easier to perform this connection. More documentation on the bash script can be found link:../../../tools/README.md[here].

To SSH connect to a VM use the `tools/passstore-vm-ssh.sh` bash script.

The 3 arguments to pass to the script are the following.

.Script options
[%header,cols="2,4"]
|===
| Command | Description

| 1: `VM_PROVIDER`

[.fuchsia]#string# / [.red]#required# 
a| Cloud provider

Choices: 

* `hetzner`
* `openstack`

| 2: `VM_NAME`

[.fuchsia]#string# / [.red]#required# 
a| Name of the VM to connect to. 

This is the inventory name of the VM.

| 3: `PASSWORD_STORE_DIR`

[.fuchsia]#string#
a| Folder where the PASSWORDSTORE database is located

*Default*: `PASSWORD_STORE_DIR` environment variable, if set. 
If this parameter is not provided and no `PASSWORD_STORE_DIR` env
variable is set the script will fail as it doesn't know the location
of the passwordstore project.

|===


.Connect to a passwordstore VM
[source,bash]
----
./tools/passstore-vm-ssh.sh openstack ${VM_NAME}
----

This should connect ot the newly created VM.

[source,bash]
======
Last login: Thu Jan 1 00:00:00 1970 from x.x.x.x
------------------

This machine is property of RedHat.
Access is forbidden to all unauthorized person.
All activity is being monitored.

Welcome to vm20210221-t01..
======
