= OpenStack Ansible Playbooks
:icons: font
:toc: left
:description: This document describes OpenStack specific playbooks.

== Before you start

[IMPORTANT]
====
The Ansible commands should be executed within the ansible folder !
====

=== Choose an image

NOTE: The list of images is identified on the link:../../../openstack/README.adoc#Images[OpenStack README file].

Different OS images are available on Openstack. To select a specific image use the `openstack.vm.image` variable override.

=== Choose a flavor

NOTE: The list of flavors is identified on the link:../../../openstack/README.adoc#Flavors[OpenStack README file].

== Playbooks

=== PasswordStore

Create OpenStack instance based on passwordstore

.openstack_vm_create_passwordstore parameters
[cols="2m,1m,5"]
|===
|Field name |Mandatory |Description

| vm_name
| x
| Name of the VM being created. Will be used both as hostname as well as Ansible Inventory name.

| openstack.vm.network
| x
| Value for the OpenStack provider network. `provider_net_shared`

| openstack.vm.image
| x
| OpenStack VM image, e.g. `Fedora-Cloud-Base-35`.

| openstack.vm.flavor"
| x
| OpenStack VM flavor (size), e.g. `m1.medium`.

| key_name
| -
| Use an existing SSH key (value) instead of creating one for the VM.

| k8s_type
| *for k8s hosts.*
| Kubernetes host type [master,worker].

| k8s_version
| *for k8s hosts.*
| Kubernetes version to be associated with the host, e.g. for version `1.23` use `123`. This is actually an Ansible Inventory group having definitions associated with each of the Kubernetes version.
|===

[source,bash]
----
$ VM_NAME=vm20210221-t01
----

[source,bash]
----
$ ansible-playbook playbook/openstack/openstack_vm_create_passwordstore.yml -e k8s_type=masters -e k8s_version=123 -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-35", "flavor": "m1.medium"}}}' -e key_name=test-adm-key -e vm_name=${VM_NAME} 
----

This playbook should finish with something like:

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=68   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
vm20210221-t01             : ok=32   changed=20   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

Monday 21 February 2022  13:01:53 +0100 (0:00:05.011)       0:12:51.042 ******* 
=============================================================================== 
openstack/init_vm : Upgrade all packages ------------------------------------------------- 305.39s
openstack/vm : Create VM instance -------------------------------------------------------- 121.94s
sec/firewalld : Install firewalld --------------------------------------------------------- 47.60s
openstack/init_vm : Install packages ------------------------------------------------------ 47.22s
openstack/init_vm : Reboot instance ------------------------------------------------------- 32.76s
Refresh the inventory so the newly added host is available -------------------------------- 21.10s
sec/sshd_port : Change SELINUX settings to allow connections to the new port --------------- 9.14s
sec/motd : Config | Install custom `/etc/motd` file ---------------------------------------- 8.24s
sec/audit : Apply auditd configuration ----------------------------------------------------- 8.06s
openstack/vm : Gather information about a previously created image with same name ---------- 7.85s
Wait for connection to host ---------------------------------------------------------------- 7.02s
openstack/vm : Wait for boot --------------------------------------------------------------- 6.55s
Gathering Facts ---------------------------------------------------------------------------- 5.77s
sec/firewalld : Enable and start firewalld ------------------------------------------------- 5.53s
Gathering Facts ---------------------------------------------------------------------------- 5.08s
sec/update : Update all packages ----------------------------------------------------------- 5.01s
sec/firewalld : firewalld - Manage firewall ports ------------------------------------------ 4.96s
sec/sshd_port : Change the ssh port number ------------------------------------------------- 4.60s
sec/firewalld : firewalld - Manage firewall services --------------------------------------- 4.58s
sec/firewalld : Restart firewalld ---------------------------------------------------------- 4.51s
....

The playbook also uses the variables defined in `roles/openstack/vm/defaults/main.yml`. Those variables can also be overridden using the syntax above.

[source,yaml]
----
include::../../roles/openstack/vm/defaults/main.yml[]
----

=== Delete a VM

To delete a VM, simply execute the `openstack_vm_remove_aggregate` playbook.

[source,bash]
----
$ ansible-playbook playbook/openstack/openstack_vm_remove_passwordstore.yml -e vm_name=${VM_NAME}
----

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2   

Monday 21 February 2022  13:07:58 +0100 (0:00:02.485)       0:00:30.900 ******* 
=============================================================================== 
openstack/vm : Gather information about a previously created image named  ------------------ 8.16s
openstack/vm : Delete  --------------------------------------------------------------------- 3.91s
openstack/vm : Delete VM volume ------------------------------------------------------------ 3.41s
openstack/vm : Delete key  from server ----------------------------------------------------- 2.93s
Push changes to the pass git database ------------------------------------------------------ 2.49s
Pull pass git database --------------------------------------------------------------------- 2.16s
openstack/vm : Set pass facts from passwordstore ------------------------------------------- 1.70s
openstack/vm : Remove existing SSH key to use with instance -------------------------------- 1.55s
openstack/vm : Find admin user home folder ------------------------------------------------- 0.98s
openstack/vm : Remove the host from the known_hosts file ----------------------------------- 0.95s
openstack/vm : stat ------------------------------------------------------------------------ 0.88s
Remove passstore entries ------------------------------------------------------------------- 0.74s
Remove local ssh keys ---------------------------------------------------------------------- 0.57s
openstack/vm : include_tasks --------------------------------------------------------------- 0.14s
Validate required variables ---------------------------------------------------------------- 0.08s
openstack/vm : Print Openstack output ------------------------------------------------------ 0.07s
openstack/vm : include_tasks --------------------------------------------------------------- 0.07s
....

=== Connect to the new instance

All the information related to the host will be managed by our ansible passwordstore roles, which also stores the ssh public and secret keys locally on the `~/.ssh` folder. On the other hand a _bash_ script has been created to make it easier to perform this connection.

To SSH connect to a VM use the `tools/passstore-vm-ssh.sh` bas script.

The 3 arguments to pass to the script are the following.

.Script options
[%header,cols="2,4"]
|===
| Command | Description

| 1: `VM_PROVIDER`

[.fuchsia]#string# / [.red]#required# 
a| Cloud provider

Choices: 

* `hetzner`
* `openstack`

| 2: `VM_NAME`

[.fuchsia]#string# / [.red]#required# 
a| Name of the VM to connect to. 

This is the inventory name of the VM.

| 3: `PASSWORD_STORE_DIR`

[.fuchsia]#string#
a| Folder where the PASSWORDSTORE database is located

*Default*: `PASSWORD_STORE_DIR`` environment variable, if set.

|===


.Connect to a passwordstore VM
[source,bash]
----
./tools/passstore-vm-ssh.sh openstack ${VM_NAME}
----

This should connect ot the newly created VM.

[source]
====
Last login: Thu Jan 1 00:00:00 1970 from x.x.x.x
------------------

This machine is property of RedHat.
Access is forbidden to all unauthorized person.
All activity is being monitored.

Welcome to vm20210221-t01..
====

