= OpenStack Ansible Playbooks
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:toc: left
:description: This document describes OpenStack specific playbooks.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Before you start

=== Choose an image

NOTE: The list of images is identified on the link:../../../openstack/README.adoc#Images[OpenStack README file].

Different OS images are available on Openstack. To select a specific image use the `openstack.vm.image` variable override.

=== Choose a flavor

NOTE: The list of flavors is identified on the link:../../../openstack/README.adoc#Flavors[OpenStack README file].

== Playbooks

=== Create a VM

Create an OpenStack instance (aka a VM) using link:../../../passwordstore/README.adoc[passwordstore] as tools to manage the credentials, information.

After creating the VM this playbook also executes the VM secure host playbook. More information link:../README.adoc#secure-host[here].

.openstack_vm_create_passwordstore parameters
[cols="20%,80%"]
|===
|Field name | Description

| `vm_name`

[.fuchsia]#string#

[.red]#required# 

a| Name of the VM being created. 

This name will be used both as hostname as well as Ansible Inventory name.

| `openstack.vm`

[.fuchsia]#map#

[.red]#required# 

a| Map with required attributes for RHOS.

Check below for more details.

|===

.openstack.vm map parameter
[cols="20%,80%"]
|===
|Field name | Description

| `flavor`

[.fuchsia]#string#

[.red]#required# 

a| RHOS Flavor specifying the CPU, RAM and DISK sizes.

| `image`

[.fuchsia]#string#

[.red]#required# 

a| OS Image to be used (e.g. `Fedora-Cloud-Base-37`).

| `network`

[.fuchsia]#string#

[.red]#required# 

a| Network provider in RHOS

|===

[source,bash]
----
VM_NAME=vm20210221-t01
----

[source,bash]
----
ansible-playbook playbook/openstack/openstack_vm_create_passwordstore.yml -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-37", "flavor": "m1.medium"}}}' -e vm_name=${VM_NAME} 
----

Although some failures might occur some might be ignored which shouldn't affect thhe process. This playbook should finish with no failed tasks.

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=68   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=1   
vm20210221-t01             : ok=32   changed=20   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

....

The playbook also uses the variables defined in `roles/openstack/vm/defaults/main.yml`. Those variables can also be overridden using the syntax above.

=== Delete a VM

To delete a VM, simply execute the `openstack_vm_remove_aggregate` playbook.

[source,bash]
----
ansible-playbook ansible/playbook/openstack/openstack_vm_remove_passwordstore.yml -e vm_name=${VM_NAME}
----

Although some failures might occur some might be ignored which shouldn't affect thhe process. This playbook should finish with no failed tasks.

[source]
....
PLAY RECAP **********************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2   

....

