== Role: Kubernetes Kind Tool

Cluster target type: K8s

=== Description

This role will install the Kubernetes `Kind` tool, next create a Kubernetes cluster.

=== Requirements

A docker daemon must be installed using the following link:../ansible/roles/docker/README.adoc[docker role] if no there.

The following python packages should be installed using `pip` tool:
- docker
- openshift

=== Role Variables

TODO

=== Example Playbook

```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml -t kind
```

To execute on the host machine, the playbook
```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml -t kind --connection=local -e override_host=localhost
```

=== How to check

To verify if `kind` is well installed, can process `ingress route` or `docker` pull/push using the local registry, please execute the following commands:

```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml \
   --connection=local -e override_host=localhost \
   -t kind
ansible-playbook ./kubernetes/ansible/k8s-misc.yml  \
   --connection=local -e override_host=localhost \
   -t ingress \
   -e target_platform=kind

ansible-playbook ./kubernetes/ansible/k8s-misc.yml \
   --connection=local -e override_host=localhost \
   -t docker_container_registry \
   -e remove=false
```

Next, pull a docker image, tag it
```bash
docker pull gcr.io/google-samples/hello-app:1.0
docker tag gcr.io/google-samples/hello-app:1.0 localhost:5000/hello-app:1.0
docker push localhost:5000/hello-app:1.0
```

and create a `Hello world` applicqtion to verify if it works
```bash
kubectl create ns demo
kubectl create deployment hello-server --image=localhost:5000/hello-app:1.0 -n demo

cat <<EOF | kubectl apply -n demo -f -
kind: Service
apiVersion: v1
metadata:
  name: hello-server
spec:
    selector:
      app: hello-server
    ports:
      - port: 8080
EOF

cat <<EOF | kubectl apply -n demo -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-server
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-server
          servicePort: 8080
EOF
```

Call the service using `curl`
```bash
curl -v http://localhost/hello
```

=== License

APL

=== Author Information

An optional section for the role authors to include contact information, or a website (HTML is not allowed).
