== Role: Kubernetes Kind Tool

Cluster target type: K8s

=== Description

This role will install the Kubernetes `Kind` tool, next create a Kubernetes cluster.

=== Requirements

A docker daemon must be installed using the following link:../docker/README.adoc[docker role] if no there.

The following python packages should be installed using `pip` tool:
- docker
- openshift

=== Role Variables

The full set of variables can be found in the link:defaults/main.yml[default file].

=== Example Playbook

To use this role, create a playbook and pass it as parameter under the `roles` section
```yaml
  - hosts: "{{ override_host | default('masters') }}"
    roles:
    - { role: kind }
```
You can also configure the role with a tag
```yaml
    - { role: 'kind', tags: 'kind'}
```

=== Usage

To play with this role, call your playbook and pass the tag to execute your role :

```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml -t kind
```

To execute the playbook on the host machine, override the `host` and setup the connection as `local`
```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml \
    --connection=local -e override_host=localhost \
    -t kind
```

=== Check if kind cluster is working

To verify if `kind` is well installed and running, if it can process `ingress route` or `docker` pull/push using the local registry,
please execute the following commands on your local machine to create the cluster and deploy the link:../ingress/README.adoc[ingress role]:

```bash
ansible-playbook ./kubernetes/ansible/k8s-misc.yml \
   --connection=local -e override_host=localhost \
   -e registry=true \
   -t kind

ansible-playbook ./kubernetes/ansible/k8s-misc.yml  \
   --connection=local -e override_host=localhost \
   -t ingress \
   -e target_platform=kind
```

Next, pull a docker image, tag it
```bash
docker pull gcr.io/google-samples/hello-app:1.0
docker tag gcr.io/google-samples/hello-app:1.0 localhost:5000/hello-app:1.0
docker push localhost:5000/hello-app:1.0
```

and create a `Hello world` application to verify if it works
```bash
kubectl create ns demo
kubectl create deployment hello-server --image=localhost:5000/hello-app:1.0 -n demo

cat <<EOF | kubectl apply -n demo -f -
kind: Service
apiVersion: v1
metadata:
  name: hello-server
spec:
    selector:
      app: hello-server
    ports:
      - port: 8080
EOF

cat <<EOF | kubectl apply -n demo -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-server
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-server
          servicePort: 8080
EOF
```

Call the service using `curl`
```bash
curl -v http://localhost/hello
```

=== License

APL

=== Author Information

An optional section for the role authors to include contact information, or a website (HTML is not allowed).
