= AWX CLI
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:icons: font
:description: AWX CLI
:source-highlighter: highlight.js

== Install CLI

Install the CLI using pip3.

[source,bash]
----
$ pip3 install --user https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
----

References: https://docs.ansible.com/ansible-tower/latest/html/towercli/usage.html#installation

== Login

The procedure to login using `awx` is the following. These docs are using the default awx user which is `admin`.

[source,bash]
----
$ export TOWER_HOST=http://<AWX_HOST>:<AWX_PORT>
$ export TOWER_USERNAME=admin
$ export TOWER_PASSWORD=$(kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode)
$ awx login  -f human
export TOWER_OAUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----

To identify `AWX_HOST` and `AWX_PORT`.

[source,bash]
----
$ AWX_HOST=$(kubectl get nodes -o jsonpath="{.items[0].status.addresses[0].address}")
$ AWX_PORT=$(kubectl get --namespace awx -o jsonpath="{.spec.ports[0].nodePort}" services awx-demo-service)
----

== Manage AWX resources

=== Organization

Create `snowdrop` organization.

[source,bash]
----
$ awx organizations create --name snowdrop --description "Snowdrop Team organization"
----

=== Inventory


==== Credential Types

Create a credential type to hold the Hetzner API key.

To create a new credential type, an `input configuration` and `inject configuration` are requried.

The *Input Configuration* specifies the input schema of the credentials. In this case only the Hetzner API Key is required.

[source,json]
----
include::conf/cred-type-hetzner-inputs.json[]
----

The *Injector Configuration* specifies how the credentials are injected in the execution jobs. In this case we'll create an `HETZNER_API_TOKEN` with the token.

[source,json]
----
include::conf/cred-type-hetzner-injectors.json[]
----


[source,bash]
----
$ awx credential_types create --kind cloud --name HetznerHCloudToken --description "Hetzner HCloud API Token" 
----

WARNING: The json options for `inputs` and `injectors`, `--inputs awx/conf/cred-type-hetzner-input.json` and `--injectors awx/conf/cred-type-hetzner-injectors.json`, are failing when executing from the command line with `argument --injectors: ./awx/conf/cred-type-hetzner-injectors.json is not valid JSON or YAML` error. Because of this these `json` contents must be added by hand in the UI, for now.

References:

* https://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html

==== Credentials

Create credentials to access inventories.

TIP: Gather the returning `id` for the created credentials for future use.

[source,bash]
----
$ awx credentials create --organization snowdrop --name openstack-jenkins --credential_type "OpenStack"  --inputs '{"username": "yyyyyyyyyyyyyy", "password": "xxxxxxxxxxxxxxxxxxxx", "project": "spring-boot-jenkins", "project_domain_name": "redhat.com", "domain": "redhat.com", "host": "https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000"}' 
----

Gather the returning `id` for the created credentials for future use.

[source,json]
----
{
     "id": 4,
     "type": "credential",
     "kind": "openstack"
}
----

[source,bash]
----
$ awx credentials create --organization snowdrop --name hetzner-hcloud --credential_type "HetznerHCloudToken"  --inputs '{"hetzner_api_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}'
----

[source,json]
----
{
     "id": 5,
     "type": "credential"
}
----

==== Projects

https://github.com/hg8496/ansible-hcloud-inventory.git

[source,bash]
----
$ awx projects create --name HetznerDynamicInventory --description "Hetzner Dynamic Inventory" --scm_type git --scm_url "https://github.com/hg8496/ansible-hcloud-inventory.git" --organization snowdrop
----

==== Inventories

Create the Openstack and Hetzner inventories.

[source,bash]
----
$ awx inventory create --name OpenStack --description "OpenStack Jenkins" --organization snowdrop
$ awx inventory create --name Hetzner --description "Hetzner Snowdrop" --organization snowdrop
----

Create inventory sources.

WARNING: The `credential ID` is the one for the *Openstack* credentials identified previously.

[source,bash]
----
$ awx inventory_sources create --name OpenStack --description "OpenStack" --source openstack --inventory OpenStack --update_on_launch true --overwrite true --overwrite_vars false --credential 4
----

Create inventory source for the Hetzner dynamic inventory.

WARNING: The `credential ID` is the one for the *Hetzner HCloud API Token* credentials identified previously.

[source,bash]
----
$ awx inventory_sources create --name Hetzner --description "Hetzner" --source scm --inventory Hetzner --update_on_launch true --overwrite true --update_on_project_update false --overwrite_vars false --credential 5 --source_project HetznerDynamicInventory
----

=== Credentials

Create credentials to access github repositories

[source,bash]
----
$ awx credentials create --name a-github-user --credential_type "GitHub Personal Access Token"  --inputs '{"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}' --organization snowdrop
----

=== Notifications

[source,bash]
----
$ awx notification_templates create --name Snowdrop --description "Snowdrop Team" --organization snowdrop --notification_type email  --inputs '{"host": "smtp.corp.redhat.com", "port": "25", "username": "snowdrop-releasing-team@redhat.com", "password": "", "use_tls": False, "use_ssl": False, "sender": "snowdrop-releasing-team@redhat.com", "recipients": "antcosta@redhat.com"}'

----

=== Playbooks

==== Create VM

[source,bash]
----
$ awx projects create --organization snowdrop --name K8sInfraProject --description "Snowdrop K8S Infra project" --scm_type git --scm_url "https://github.com/snowdrop/k8s-infra.git" --scm_update_on_launch true
----

[source,bash]
----
$ awx job_templates create --name CreateVMOpenstack --description "Create OpenStack VM" --job_type run --inventory Localhost --project K8sInfraProject --playbook "ansible/playbook/openstack_vm_create_awx.yml" --survey_enabled true --use_fact_cache true
                                [--scm_branch TEXT] [--forks INTEGER]
                                [--limit TEXT] [--verbosity {0,1,2,3,4,5}]
                                [--extra_vars JSON/YAML] [--job_tags TEXT]
                                [--force_handlers BOOLEAN] [--skip_tags TEXT]
                                [--start_at_task TEXT] [--timeout INTEGER]
                                [--use_fact_cache BOOLEAN]
                                [--host_config_key TEXT]
                                [--ask_scm_branch_on_launch BOOLEAN]
                                [--ask_diff_mode_on_launch BOOLEAN]
                                [--ask_variables_on_launch BOOLEAN]
                                [--ask_limit_on_launch BOOLEAN]
                                [--ask_tags_on_launch BOOLEAN]
                                [--ask_skip_tags_on_launch BOOLEAN]
                                [--ask_job_type_on_launch BOOLEAN]
                                [--ask_verbosity_on_launch BOOLEAN]
                                [--ask_inventory_on_launch BOOLEAN]
                                [--ask_credential_on_launch BOOLEAN]
                                [--survey_enabled BOOLEAN]
                                [--become_enabled BOOLEAN]
                                [--diff_mode BOOLEAN]
                                [--allow_simultaneous BOOLEAN]
                                [--custom_virtualenv TEXT]
                                [--job_slice_count INTEGER]
                                [--webhook_service {,github,gitlab}]
                                [--webhook_credential ID]
----

== References

* https://docs.ansible.com/ansible-tower/latest/html/towercli/index.html
