= Hetzner Ansible
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 2

== Introduction

This document describes the Ansible playbooks implemented.

=== Scope

Describe the steps to install the hetzner client and provision hetzner cloud VMs.

== Requirements

Read the link:README.adoc[] and link:README-cloud.adoc[] documents.

== Playbooks

Although there are several playbooks available, for creating and deleting hetzner VMs 2 of them should be used. Other playbooks are used as dependencies for these main playbooks

[#hetzner_vm_create]
=== Create Passstore VM 

The playbook for creating a passwordstore based VM is `hetzner_vm_create_passwordstore.yml` which is located at `ansible/playbook/hetzner/`.

To create a new VM execute the following command

.Create passwordstore VM on Hetzner
[source,bash]
----
ansible-playbook ansible/playbook/hetzner/hetzner_vm_create_passwordstore.yml -e vm_name=snowdrop-vm -e k8s_type=masters -e k8s_version=123 -e salt_text=$(gpg --gen-random --armor 1 20) -e vm_image=fedora-37 -e server_type=cx21
----

The parameters are the following.

.Script options
[%header,cols="2,4"]
|===
| Parameter | Description

| `k8s_type`

[.fuchsia]#string#
a| Type of k8s node

Choices: 

* `master`
* `node`

| `k8s_version`

[.fuchsia]#string#
a| Kubernetes version

Choices: 

* 124: Kubernetes 1.24
* 123: Kubernetes 1.23
* 121: Kubernetes 1.21
* 119: Kubernetes 1.19

[WARNING]
====
The kubernetes version must be mapped at Ansible Inventory level, 
on the `hosts.yaml` file located at the `ansible/inventory` subfolder.
====

| `salt_text`

[.fuchsia]#string#

[.red]#required# 

a| Salt to be used on the generation of the host user password. 

Usually the following script is used: `$(gpg --gen-random --armor 1 20)`.

| `server_type`

[.fuchsia]#string#

a| The flavor of the servier in terms of CPU and RAM.

More information at: https://docs.hetzner.com/cloud/servers/overview/#shared-vcpu

| `vm_image`

[.fuchsia]#string#
a| The base image to generate the VM from (OS). 

More information at:

* https://docs.hetzner.com/robot/dedicated-server/operating-systems/standard-images/.
* https://docs.hetzner.com/cloud/servers/overview/#operating-systems

| `vm_name`

[.fuchsia]#string# 

[.red]#required# 

a| Name to be given to the VM.

|===


[NOTE]
====

More information on the `k8s_type`

.Click to see the sample `yaml` file contents
[%collapsible]
======
[source,yaml]
----
include::../ansible/inventory/hosts.yml[tag=k8s_type]
----
======
====

[NOTE]
====

More information on the `k8s_version`

.Click to see the sample `yaml` file contents
[%collapsible]
======
[source,yaml]
----
include::../ansible/inventory/hosts.yml[tag=k8s_version]
----
======
====

[#hetzner_vm_delete]
=== Delete Passstore VM 

The playbook for deleting a passwordstore based VM is `hetzner_vm_delete_passwordstore.yml` which is located at `ansible/playbook/hetzner/`.

To delete a new VM execute the following command.

.Delete a passwordstore VM on Hetzner
[source,bash]
----
ansible-playbook ansible/playbook/hetzner/hetzner_vm_delete_passwordstore.yml -e vm_name=snowdrop-vm
----

== Configuration Playbooks

[#hetzner-init-context]
=== Init the hetzner context

Initializes the Hetzner context.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml
----

This playbook has the following variables.

[%header,cols="2m,1,1,3"]
|===
| Variable | Required | Prompt | Meaning 

| hetzner_context_name | x | x | context name 
| hetzner_token | x | x | The token to register with Hetzner. 
|===

Each of the Ansible prompts can be replaced by defining it's value as an extra variable of the playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml -e hetzner_context_name=mycontext -e hetzner_token=mytoken 
----

== Other Playbooks

Several playbooks have been created to interact with Hetzner which are described in this section.

The playbooks with `_passwordstore` suffix have been developed with storing information on a https://www.passwordstore.org/[pass] database.


=== hetzner_ssh_key_create

Prior to creating a new VM, the SSH key generated by the Ansible Inventory must be added to the Hetzner SSH Key repository. This SSH will then be used in the server creation.

This is accomplished using the  [hetzner-create-ssh-key](ansible/hetzner-create-ssh-key.yml) playbook which will create an SSH Key with the name of the 

.`hetzner_ssh_key_create` playbook options
[cols="2,4"]
|===
| `vm_name`

[.fuchsia]#string# 

[.red]#required# 

a| Name of the VM to be created at hetzner. 

|===

.`hetzner_ssh_key_create` playbook sample
[]
====

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-ssh-key.yml -e vm_name=${VM_NAME}
----

====
