= Hetzner Ansible
:icons: font
:toc: left

== Introduction

This document describes the Ansible playbooks implemented.

=== Scope

Describe the steps to install the hetzner client and provision hetzner cloud VMs.

== Requirements

Read the link:README.adoc[] and link:README-cloud.adoc[] documents.

== Playbooks

Although there are several playbooks available, for creating and deleting hetzner VMs 2 of them should be used. Other playbooks are used as dependencies for these main playbooks

=== Create Passstore VM 

The playbook for creating a passwordstore based VM is `hetzner_vm_create_passwordstore.yml` which is located at `ansible/playbook/hetzner/`.

To create a new VM execute the following command

.Create passwordstore VM on Hetzner
[source,bash]
----
ansible-playbook ansible/playbook/hetzner/hetzner_vm_create_passwordstore.yml -e vm_name=snowdrop-vm -e k8s_type=masters -e k8s_version=123 -e salt_text=$(gpg --gen-random --armor 1 20) -e vm_image=fedora-37 -e server_type=cx21
----

The parameters are the following.

.Script options
[%header,cols="2,4"]
|===
| Parameter | Description

| `vm_name`

[.fuchsia]#string# 

[.red]#required# 
a| Name to be given to the VM.

| `k8s_type`

[.fuchsia]#string#
a| Type of k8s node

Choices: 

* `master`
* `node`

| `k8s_version`

[.fuchsia]#string#
a| Kubernetes version

Choices: 

* 124: Kubernetes 1.24
* 123: Kubernetes 1.23
* 121: Kubernetes 1.21
* 119: Kubernetes 1.19

[WARNING]
====
The kubernetes version must be mapped at Ansible Inventory level, 
on the `hosts.yaml` file located at the `ansible/inventory` subfolder.
====

| `salt_text`

[.fuchsia]#string#
a| Salt to be used on the generation of the host user password. 

Usually the following script is used: `$(gpg --gen-random --armor 1 20)`.

| `vm_image`

[.fuchsia]#string#
a| The base image to generate the VM from (OS). 

More information at:

* https://docs.hetzner.com/robot/dedicated-server/operating-systems/standard-images/.
* https://docs.hetzner.com/cloud/servers/overview/#operating-systems

| `server_type`

[.fuchsia]#string#

a| The flavor of the servier in terms of CPU and RAM.

More information at: https://docs.hetzner.com/cloud/servers/overview/#shared-vcpu

|===


[NOTE]
====

More information on the `k8s_type`

.Click to see the sample `yaml` file contents
[%collapsible]
======
[source,yaml]
----
include::../ansible/inventory/hosts.yml[tag=k8s_type]
----
======
====

[NOTE]
====

More information on the `k8s_version`

.Click to see the sample `yaml` file contents
[%collapsible]
======
[source,yaml]
----
include::../ansible/inventory/hosts.yml[tag=k8s_version]
----
======
====

=== Delete Passstore VM 

The playbook for deleting a passwordstore based VM is `hetzner_vm_delete_passwordstore.yml` which is located at `ansible/playbook/hetzner/`.

To delete a new VM execute the following command.

.Delete a passwordstore VM on Hetzner
[source,bash]
----
ansible-playbook ansible/playbook/hetzner/hetzner_vm_delete_passwordstore.yml
----

== Configuration Playbooks

[#hetzner-init-context]
=== Init the hetzner context

Initializes the Hetzner context.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml
----

This playbook has the following variables.

[%header,cols="2m,1,1,3"]
|===
| Variable | Required | Prompt | Meaning 

| hetzner_context_name | x | x | context name 
| hetzner_token | x | x | The token to register with Hetzner. 
|===

Each of the Ansible prompts can be replaced by defining it's value as an extra variable of the playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml -e hetzner_context_name=mycontext -e hetzner_token=mytoken 
----

== VM Playbooks

Several playbooks have been created to interact with Hetzner which are described in this section.

The playbooks with `_passwordstore` suffix have been developed with storing information on a https://www.passwordstore.org/[pass] database.


=== hetzner_ssh_key_create

Prior to creating a new VM, the SSH key generated by the Ansible Inventory must be added to the Hetzner SSH Key repository. This SSH will then be used in the server creation.

This is accomplished using the  [hetzner-create-ssh-key](ansible/hetzner-create-ssh-key.yml) playbook which will create an SSH Key with the name of the VM.

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| vm_name | x | | x | Name of the VM to be created at hetzner. 
|===

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-ssh-key.yml -e vm_name=${VM_NAME}
----

=== hetzner_ssh_key_delete.yml


=== hetzner-start-server.yml

=== hetzner-stop-server.yml

=== hetzner_vars.yml

[#hetzner_vm_create]
=== hetzner_vm_create

The task of creating the hetzner context is also available through an Ansible playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-server.yml
----

This will present some prompts which can be replaced by environment variables. 

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| hetzner_context_name | x | snowdrop | | Context name for hcloud. 
| override_public_key |  | |  | Use a *local custom key* instead the default one. 
| salt_text | x | | x | Salt and pepper. 
| server_type | | cx31 |  | Server type. The list can be obtained using `hcloud server-type list`. Usually cx31 
| vm_image | | centos-7 |  | Hetzner image to be used as source (centos-7,...) 
| vm_name | x | | x | Name of the VM to be created at hetzner. 
|===

Each of the Ansible prompts can be replaced by defining it's value as an extra variable of the playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-server.yml -e vm_name=${VM_NAME} \
-e salt_text=$(head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1) \
-e hetzner_context_name=snowdrop
----
**REMARK**: For mac's users, please execute the following command before `export LC_ALL=C`

Once this task is finished it's mandatory to launch server securization, see the [Next steps](#next-steps) section.

2 new playbooks have been created to aggregate the operations executed by the different playbooks
, `hetzner-create-server-aggregate.yml` and `hetzner-delete-server-aggregate.yml`. Each of the playbooks invokes deployment and cleanup operations on the passwordstore inventory database, VM deployment operations and VM securization.

==== hetzner_vm_create_awx

Creates a Hetzner VM using AWX.

NOTE: TODO

==== hetzner_vm_create_passwordstore.yml


The `hetzner-create-server-aggregate.yml` playbooks calls the following playbooks:

* `../../ansible/playbook/passstore_controller_inventory.yml` to set the VM passwordstore inventory information;
* `hetzner-create-ssh-key.yml` to create the Hetzner VM SSH keys;
* `hetzner-create-server.yml` to deploy a new server on hetzner;
* `../../ansible/playbook/sec_host.yml` to apply the securization playbook;

To create and deploy a new VM simply execute the following command on the `ansible` subfolder.

[source,bash]
----
$ ansible-playbook playbook/hetzner/hetzner_vm_create_passwordstore.yml -e vm_name=my_vm_name -e k8s_type=masters -e k8s_version=123 -e salt_text=$(gpg --gen-random --armor 1 20) -e vm_image=fedora-36 -e server_type=cx21
----

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| k8s_type | | | | Type of k8s node (masters, nodes). Will be used to set the ansible inventory groups. 
| k8s_version | | | | K8s version to be later installed. Will be used to set the ansible inventory groups. 
| salt_text | x | | | Salt and pepper. 
| vm_name | x |  | | Name of the VM to be craated. This will be both the name on Hetzner as well as on the inventory 
|===

[#hetzner_vm_delete]
=== hetzner_vm_delete

Delete a hetzner server vm.

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| hetzner_context_name | x | snowdrop | | Context name for hcloud. 
| vm_name | x | | x | Name of the VM to be deleted from hetzner. 
|===

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-server.yml -e vm_name=my-name -e hetzner_context_name=snowdrop
----

After that, remove the Hetzner SSH key for the server.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-ssh-key.yml -e vm_name=my-name
----

As well as the inventory entries for the server.

[source,bash]
----
$ ansible-playbook ansible/playbook/passstore_controller_inventory_remove.yml -e vm_name=my-name -e pass_provider=hetzner
----


==== hetzner_vm_delete_awx.yml

==== hetzner_vm_delete_passwordstore.yml


The `hetzner_vm_delete_passwordstore.yml` playbooks calls the following playbooks:

* `hetzner-delete-server.yml` to delete the server from hetzner;
* `hetzner-delete-ssh-key.yml` to delete the Hetzner VM SSH keys;
* `../../ansible/playbook/passstore_controller_inventory.yml` to clean th VM information from the passwordstore inventory;

Removing a VM also has an aggregate playbook, requiring only the `vm_name` parameter.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-server-aggregate.yml -e vm_name=my_vm
ansible-playbook playbook/hetzner/hetzner_vm_delete_passwordstore.yml -e vm_name=${VM_NAME}
----



