= Hetzner Ansible
:icons: font
:toc: left

== Introduction

This document describes the Ansible playbooks implemented.

=== Scope

Describe the steps to install the hetzner client and provision hetzner cloud VMs.

== Requirements

Read the link:README.adoc[] and README-cloud documents.

==  Playbooks

.Playbook list
[%header,cols="2m,1,3"]
|===
| Playbook file | Type | Description

| <<hetzner-init-context>>
| Configuration
| Initializes the Hetzner Context on a host.

| hetzner_ssh_key_create.yml
| VM (Optional)
| Creates an new SSH key on Hetzner.

| hetzner_ssh_key_delete.yml
| VM (Optional)
| Deletes a Hetzner SSH key.

| hetzner-start-server.yml
| VM
| Start Hetzner VM

| hetzner-stop-server.yml
| VM
| Stop Hetzner VM

| hetzner_vars.yml
| N/A
| Internal playbook to define Hetzner variables.

| <<hetzner_vm_create>>
| VM
| Playbooks for creating VMs on Hetzner.

| <<hetzner_vm_delete>>
| VM
| Playbooks for deletong Hetnzer VMs.

|===

== Configuration Playbooks

[#hetzner-init-context]
=== Init the hetzner context

Initializes the Hetzner context.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml
----

This playbook has the following variables.

[%header,cols="2m,1,1,3"]
|===
| Variable | Required | Prompt | Meaning 

| hetzner_context_name | x | x | context name 
| hetzner_token | x | x | The token to register with Hetzner. 
|===

Each of the Ansible prompts can be replaced by defining it's value as an extra variable of the playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-init-context.yml -e hetzner_context_name=mycontext -e hetzner_token=mytoken 
----

== VM Playbooks

Several playbooks have been created to interact with Hetzner which are described in this section.

The playbooks with `_passwordstore` suffix have been developed with storing information on a https://www.passwordstore.org/[pass] database.


=== hetzner_ssh_key_create

Prior to creating a new VM, the SSH key generated by the Ansible Inventory must be added to the Hetzner SSH Key repository. This SSH will then be used in the server creation.

This is accomplished using the  [hetzner-create-ssh-key](ansible/hetzner-create-ssh-key.yml) playbook which will create an SSH Key with the name of the VM.

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| vm_name | x | | x | Name of the VM to be created at hetzner. 
|===

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-ssh-key.yml -e vm_name=${VM_NAME}
----

=== hetzner_ssh_key_delete.yml


=== hetzner-start-server.yml

=== hetzner-stop-server.yml

=== hetzner_vars.yml

[#hetzner_vm_create]
=== hetzner_vm_create

The task of creating the hetzner context is also available through an Ansible playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-server.yml
----

This will present some prompts which can be replaced by environment variables. 

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| hetzner_context_name | x | snowdrop | | Context name for hcloud. 
| override_public_key |  | |  | Use a *local custom key* instead the default one. 
| salt_text | x | | x | Salt and pepper. 
| server_type | | cx31 |  | Server type. The list can be obtained using `hcloud server-type list`. Usually cx31 
| vm_image | | centos-7 |  | Hetzner image to be used as source (centos-7,...) 
| vm_name | x | | x | Name of the VM to be created at hetzner. 
|===

Each of the Ansible prompts can be replaced by defining it's value as an extra variable of the playbook.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-create-server.yml -e vm_name=${VM_NAME} \
-e salt_text=$(head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1) \
-e hetzner_context_name=snowdrop
----
**REMARK**: For mac's users, please execute the following command before `export LC_ALL=C`

Once this task is finished it's mandatory to launch server securization, see the [Next steps](#next-steps) section.

2 new playbooks have been created to aggregate the operations executed by the different playbooks
, `hetzner-create-server-aggregate.yml` and `hetzner-delete-server-aggregate.yml`. Each of the playbooks invokes deployment and cleanup operations on the passwordstore inventory database, VM deployment operations and VM securization.

==== hetzner_vm_create_awx

Creates a Hetzner VM using AWX.

NOTE: TODO

==== hetzner_vm_create_passwordstore.yml


The `hetzner-create-server-aggregate.yml` playbooks calls the following playbooks:

* `../../ansible/playbook/passstore_controller_inventory.yml` to set the VM passwordstore inventory information;
* `hetzner-create-ssh-key.yml` to create the Hetzner VM SSH keys;
* `hetzner-create-server.yml` to deploy a new server on hetzner;
* `../../ansible/playbook/sec_host.yml` to apply the securization playbook;

To create and deploy a new VM simply execute the following command on the `ansible` subfolder.

[source,bash]
----
$ ansible-playbook playbook/hetzner/hetzner_vm_create_passwordstore.yml -e vm_name=my_vm_name -e k8s_type=masters -e k8s_version=123 -e salt_text=$(gpg --gen-random --armor 1 20) -e vm_image=fedora-36 -e server_type=cx21
----

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| k8s_type | | | | Type of k8s node (masters, nodes). Will be used to set the ansible inventory groups. 
| k8s_version | | | | K8s version to be later installed. Will be used to set the ansible inventory groups. 
| salt_text | x | | | Salt and pepper. 
| vm_name | x |  | | Name of the VM to be craated. This will be both the name on Hetzner as well as on the inventory 
|===

[#hetzner_vm_delete]
=== hetzner_vm_delete

Delete a hetzner server vm.

[%header,cols="2m,1,1,1,3"]
|===
| Variable | Required | Default | Prompt | Meaning 

| hetzner_context_name | x | snowdrop | | Context name for hcloud. 
| vm_name | x | | x | Name of the VM to be deleted from hetzner. 
|===

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-server.yml -e vm_name=my-name -e hetzner_context_name=snowdrop
----

After that, remove the Hetzner SSH key for the server.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-ssh-key.yml -e vm_name=my-name
----

As well as the inventory entries for the server.

[source,bash]
----
$ ansible-playbook ansible/playbook/passstore_controller_inventory_remove.yml -e vm_name=my-name -e pass_provider=hetzner
----


==== hetzner_vm_delete_awx.yml

==== hetzner_vm_delete_passwordstore.yml


The `hetzner_vm_delete_passwordstore.yml` playbooks calls the following playbooks:

* `hetzner-delete-server.yml` to delete the server from hetzner;
* `hetzner-delete-ssh-key.yml` to delete the Hetzner VM SSH keys;
* `../../ansible/playbook/passstore_controller_inventory.yml` to clean th VM information from the passwordstore inventory;

Removing a VM also has an aggregate playbook, requiring only the `vm_name` parameter.

[source,bash]
----
$ ansible-playbook hetzner/ansible/hetzner-delete-server-aggregate.yml -e vm_name=my_vm
ansible-playbook playbook/hetzner/hetzner_vm_delete_passwordstore.yml -e vm_name=${VM_NAME}
----



