= Role: Openshift Container Platform Cluster
:icons: font
:revdate: {docdate}
:toc: left

== Description

This role installs an OCP cluster on a RHOS cloud.

== Requirements

* OpenShift Pull Secret that can be obtained from https://console.redhat.com/openshift/install/pull-secret
* `openstack.cloud` Ansible module installed: `ansible-galaxy collection install openstack.cloud`

== Role Variables

[%header,cols="1,4"]
|===
| Parameter | Comments

| `installation_dir`

[.fuchsia]#string#
a| Installation folder for the OCP files, where `ocp_install_dir` is a role variable.

_Default:_ `<ocp_root_directory>/<ocp_cluster_name>`

| `ocp_cluster_name`

[.fuchsia]#string#
a| Name to be applied to the OCP cluster. It will be used as a prefix in the VM names.

_Default:_ `ocp`

| `ocp_cluster_user_admin_name`

[.fuchsia]#string#
a| Admin user to be created in the OCP cluster.

_Default:_ `admin`

| `ocp_cluster_user_admin_pw`

[.fuchsia]#string#
a| Password for the admin user.

_Default:_ `admin`

| `ocp_cluster_user_dev_name`

[.fuchsia]#string#
a| Developer user to be created in the OCP cluster.

_Default:_ `snowdrop`

| `ocp_cluster_user_dev_pw`

[.fuchsia]#string#
a| Password for the developer user.

_Default:_ `snowdrop`

| `ocp_master_nodes`

[.fuchsia]#int#
a| Number of master nodes in the OCP cluster.

_Default:_ `3`

| `ocp_root_directory`

[.fuchsia]#string#
a| Root folder for the installation. Under this folder 2 subfolders will be created:

* `bin`: will store the executables for the installation which are `openshift-install`, `oc` and `kubectl`.
* `<cluser_name>`: will store the installation data

_Default:_ `/opt/ocp`

| `ocp_version`

[.fuchsia]#string#
a| OCP version to install

_Default:_ `4.13.9`

| `ocp_worker_nodes`

[.fuchsia]#int#
a| Number of worker nodes in the OCP cluster.

* Can be 0
* *_Default:_ `3`*

| `openstack_flavor_compute`

[.fuchsia]#string#
a| 

_Default:_ `ocp4.compute`

| `openstack_flavor_control_plane`

[.fuchsia]#string#
a| 

_Default:_ `ocp4.control`

| `openstack_network_provider`

[.fuchsia]#string#
a| 

_Default:_ `provider_net_cci_13`

| `state`

[.fuchsia]#string# / [.red]#required# 
a| State of the cluster.

Choices: 

* `present` to install the cluster
* `absent` to remove the cluster

|===

[NOTE]
======
The full set of predefined variables can be found in the link:defaults/main.yml[default file].

.Check the `defaults/main.yml` file contents
[%collapsible]
====

[source,yaml]
----
include::defaults/main.yml[]
----

====

======

== Example Playbook

.Sample playbook for deploying OCP on RHOS
[source,yaml]
----
- name: "Install OCP"
  hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: "Set openstack_auth facts"
      set_fact:
        openstack_auth: 
          openstack_project_name: "rhos_project"
          openstack_console_user:  "rhos_user"
          openstack_console_password: "rhos_password"
          openstack_user_domain:  "rhos_user_domain"
          openstack_project_domain: "rhos_project_domain"
          openstack_os_auth_url: "rhos_auth_url"
          
  tasks:
    - name: "Deploy OCP"
      import_role:
        name: 'ocp_cluster'
      vars:
        state: present
----

.Sample playbook for removing OCP deployed on RHOS
[source,yaml]
----
- name: "Uninstall OCP"
  hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: "Set openstack_auth facts"
      set_fact:
        openstack_auth: 
          openstack_project_name: "rhos_project"
          openstack_console_user:  "rhos_user"
          openstack_console_password: "rhos_password"
          openstack_user_domain:  "rhos_user_domain"
          openstack_project_domain: "rhos_project_domain"
          openstack_os_auth_url: "rhos_auth_url"
          
  tasks:
    - name: "Deploy OCP"
      import_role:
        name: 'ocp_cluster'
      vars:
        state: absent
----

== License

https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0]

== Author Information

This role has been created by the https://github.com/orgs/snowdrop/teams[Snowdrop team].
