= Red Hat Open Stack
Snowdrop Team
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 3
:description: Red Hat Open Stack
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

[.lead]
This document describes the tools implemented on this project, that help 
 provision and maintain infrastructure on a RHOS Platform.

The tools implemented are the following:

* Provision VMs on RHOSP
* Provision OCP cluster on RHOSP

=== Other references

The OpenStack CLI tool comes very handy to perform several checks and 
 information collection. We've created the link:openstack-cli.adoc[RHOSP CLI] 
 document to describe some of the most used commands.

[glossary]
== Terminology

[glossary]
FS:: Filesystem
OCP:: OpenShift Container Platform
RHOSP:: Red Hat OpenStack Platform

== Requirements
// tag::rhos_prerequisites[]

This project uses several Python libraries and Ansible Galaxy collections. 
 The best way to solve the requirements needed to use the RHOSP 
 Ansible resources from this document is to install the provided 
 python requirements files. Moreover using Python Virtual Environment can also be used. For more information check the link:../ansible/README.adoc#python-venv[Python Virtual Env] section on our Ansible README. If you 
 do so you can skip the manual installation section.

=== Manual installation

The following python packages are needed:

- https://github.com/micheles/decorator/blob/master/docs/documentation.md#usefulness-of-decorators[decorator]
- https://pypi.org/project/openstacksdk/[openstacksdk] (Version: 1.2.0)

and can be installed using pip

[source,bash]
----
sudo pip3 install -r requirements.txt
----

like also the `openstack.cloud` Ansible collection.

[source,bash]
----
ansible-galaxy collection install openstack.cloud
----
// end::rhos_prerequisites[]

=== Passwordstore

Passwordstore is used during the execution of the ansible playbooks when RHOSP 
 instances or OCP clusters are created/removed. In one hand it 
 provides information for the deployment process, such as RHOSP authentication, 
 and also to store the results of the process and be used as Ansible 
 inventory.

[NOTE]
====
All RHOSP information will be stored under the `/openstack` passwordstore folder.
====

=== RHOSP authentication

The authentication consists in collecting the authentication information 
 and storing it in 2 Ansible facts, for later use in Ansible roles.

.RHOSP authentication information
[%header,cols="20%m,80%"]
|===
| Variable | Meaning

| rhos_auth
a| Authentication information

The fields to provide in this dictionary will depend on the selected 
 _Authentication Type_.

| rhos_auth_type
a| Authentication type

Check the `openstack` CLI man page for available types.

* `v3password`
* `v3token`
* ...

|===

.Click to see sample Ansible Playbook for setting the RHOSP authentication facts
[%collapsible]
======
[source,yaml]
----
include::../ansible/playbook/openstack/openstack_auth_passstore_v3password.yml[]
----
======

== Ansible Inventory

All the information related to the host will be managed by our ansible passwordstore link:../../roles/passstore[roles] and link:../passstore[playbooks]. The current implementation also stores the SSH public and secret keys locally on each `~/.ssh` folder. 

== Preparing the Provisioning

The main goal of the RHOSP tools is to provision VM instances and 
 store their information on the team passwordstore inventory for 
 later use by the team members.

Prior to creating an actual VM, aspects such as the OS image and 
 the sizing of the VM must be decided.

[NOTE]
====
The examples provided here are photos of a specific time frame. To get 
 updated lists of images and flavors check you RHOSP cluster using either 
 the RHOSP console or the link:openstack-cli.adoc[RHOSP CLI].
====

=== OS Image

[quote,RedHat RHOSP Documentation,The Image service (glance)]
A virtual machine image is a file that contains a virtual disk with a bootable operating system installed.

To identify available images and choose which one to use check our docs on the link:openstack-cli.adoc[RHOSP CLI tool] which describe some of the most used commands.

=== Flavors

[quote,RedHat RHOSP Documentation,Flavors]
In OpenStack, flavors define the compute, memory, and storage capacity of nova computing instances. To put it simply, a flavor is an available hardware configuration for a server. It defines the size of a virtual server that can be launched.

Reduced list of flavors obtained from our RHOSP cluster.

.OpenStack Flavor information
[%header,cols="2m,1,1,1,1,1"]
|===
| Flavor | VCPUS | RAM | Total Disks | Root Disk | Ephemeral Disk

| m1.medium           | 2  | 4 GB  | 40 GB | 40 GB | 0 GB 
| ci.m1.medium        | 2  | 4 GB  | 40 GB | 40 GB | 0 GB 
| ci.m1.medium.large  | 4  | 4 GB  | 16 GB | 16 GB | 0 GB 
| ci.m4.xlarge	      | 4  | 16 GB | 40 GB | 40 GB | 0 GB 
| ci.m5.large         | 16 | 32GB  | 40GB  | 40GB  | 0GB 
| g.standard.xxl      | 12 | 24GB  | 120GB | 120GB | 0GB 
| ocp4.single-node    | 24 | 48GB  | 200GB | 200GB | 0GB 
| ocp4.control        | 4  | 16GB  | 100GB | 100GB | 0GB 
| ocp4.compute        | 2  | 8GB   | 100GB | 100GB | 0GB 
| ocp4.bootstrap      | 4  | 16GB  | 100GB | 100GB | 0GB 
|===

== VM Provisioning

Once the system configuration is identified it's time to create a VM. 
 Execution instructions to perform the VM provision operations are available 
 on the link:../ansible/playbook/openstack/README.adoc[OpenStack Ansible Playbooks] document.

== Connect to a RHOSP instance

To improve usability link:../../../tools/passstore-vm-ssh.sh[this] bash script has been created to make it easier to perform this connection. More documentation on the bash script can be found link:../../../tools/README.md[here].

To SSH connect to a VM use the `tools/passstore-vm-ssh.sh` bash script.

The 3 arguments to pass to the script are the following.

.Script options
[%header,cols="2,4"]
|===
| Command | Description

| 1: `VM_PROVIDER`

[.fuchsia]#string# / [.red]#required# 
a| Cloud provider

Choices: 

* `openstack`

| 2: `VM_NAME`

[.fuchsia]#string# / [.red]#required# 
a| Name of the VM to connect to. 

This is the inventory name of the VM.

| 3: `PASSWORD_STORE_DIR`

[.fuchsia]#string#
a| Folder where the PASSWORDSTORE database is located

*Default*: `PASSWORD_STORE_DIR` environment variable, if set. 
If this parameter is not provided and no `PASSWORD_STORE_DIR` env
variable is set the script will fail as it doesn't know the location
of the passwordstore project.

|===

.Connect to a passwordstore VM
[source,bash]
----
./tools/passstore-vm-ssh.sh openstack vm20210221-t01
----

This should connect ot the newly created VM.

====
----------------------------
Last login: Thu Jan 1 00:00:00 1970 from x.x.x.x
------------------

This machine is property of RedHat.
Access is forbidden to all unauthorized person.
All activity is being monitored.

Welcome to vm20210221-t01..
----------------------------
====

== Deploy OCP on RHOSP

Another tool on the set of RHOSP tools allows deploying an OCP 
 cluster on RHOSP. This set of Ansible playbooks will provision an 
 OCP cluster, tailores to the selected size, and also provision a 
 jump server that will allow ssh connection to each of the cluster 
 nodes.

To perform this installation check the link:../ansible/playbook/ocp/README.adoc[OCP on RHOSP Ansible Playbooks] document.
