= Passwordstore Database Implementation
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:toc: left
:description: This document describes the passwordstore implementation.
database in this project.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the implementation of the passwordstore in the project.

== Overview

The pass implementation uses a link:https://www.passwordstore.org/[pass] 
database to store the Ansible inventory and other infrastructure related
information.

=== Ansible pass Structure

Besides storing other information, the pass database also stores the team
Ansible Inventory.

The structure of the inventory is the following:

[width="100%",cols="20%,20%,10%,50%",options="header",]
|===
| Level | Type | Data | Comments

| Level 1 
| Directory
| Provider
a| The name of the provider is used to split VMs for different providers.

Currently only `openstack` is a tested provider.

[WARNING]
====
Although the `hetzner` provided is also implemented it has been abandoned and will be removed from the pass database.
====

| Level 3
| Directory
| VM
| Name that will be given to the VM. It will also be used as the 
Ansible Host name.

| Level 3
| Entry
| Ansible attributes
| One entry for each Ansible attribute that will be translated into a
environment variable.

| Level 3
| Directory
| `groups`
| List of groups into which the host will be associated to.

| Level 4 (under `groups`)
| Entries
| `group name`
| One entry for each group the host will be associated with. 

The entry name is the group name.

|===


=== Ansible Inventory

The ansible inventory obtained from the pass database is built using the python
script located at link:../ansible/inventory/pass_inventory.py[../ansible/inventory/pass_inventory.py].

== Ansible Playbooks

Information on the available playbooks is available link:../ansible/playbook/passstore/README.adoc[here].


== Connect to a host instance

All the information related to the hosts will be stored in the passwrodstore Ansible inventory. The current implementation also stores the ssh public and secret keys locally on each `~/.ssh` folder. To improve usability link:../../../tools/passstore-vm-ssh.sh[this] bash script has been created to make it easier to perform this connection. More documentation on the bash script can be found link:../../../tools/README.md[here].

To SSH connect to a VM use the `tools/passstore-vm-ssh.sh` bash script.

The 3 arguments to pass to the script are the following.

.Script options
[%header,cols="2,4"]
|===
| Command | Description

| 1: `VM_PROVIDER`

[.fuchsia]#string# / [.red]#required# 
a| Cloud provider

Choices: 

* `hetzner`
* `openstack`

| 2: `VM_NAME`

[.fuchsia]#string# / [.red]#required# 
a| Name of the VM to connect to. 

This is the inventory name of the VM.

| 3: `PASSWORD_STORE_DIR`

[.fuchsia]#string#
a| Folder where the PASSWORDSTORE database is located

*Default*: `PASSWORD_STORE_DIR` environment variable, if set. 
If this parameter is not provided and no `PASSWORD_STORE_DIR` env
variable is set the script will fail as it doesn't know the location
of the passwordstore project.

|===


.Connect to a passwordstore VM
[source,bash]
----
./tools/passstore-vm-ssh.sh openstack ${VM_NAME}
----

This should connect ot the newly created VM.

[source,bash]
======
Last login: Thu Jan 1 00:00:00 1970 from x.x.x.x
------------------

This machine is property of RedHat.
Access is forbidden to all unauthorized person.
All activity is being monitored.

Welcome to vm20210221-t01..
======
