= Passwordstore Database Implementation
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:toc: left
:description: This document describes the passwordstore implementation.
database in this project.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the implementation of the passwordstore in the project.

== Overview

The pass implementation uses a link:https://www.passwordstore.org/[pass] 
database to store the Ansible inventory and other infrastructure related
information.

=== Ansible pass Structure

Besides storing other information, the pass database also stores the team
Ansible Inventory.

The structure of the inventory is the following:

[width="100%",cols="20%,20%,10%,50%",options="header",]
|===
| Level | Type | Data | Comments

| Level 1 
| Directory
| Provider
a| The name of the provider is used to split VMs for different providers.

Currently only `openstack` is a tested provider.

[WARNING]
====
Although the `hetzner` provided is also implemented it has been abandoned and will be removed from the pass database.
====

| Level 3
| Directory
| VM
| Name that will be given to the VM. It will also be used as the 
Ansible Host name.

| Level 3
| Entry
| Ansible attributes
| One entry for each Ansible attribute that will be translated into a
environment variable.

| Level 3
| Directory
| `groups`
| List of groups into which the host will be associated to.

| Level 4 (under `groups`)
| Entries
| `group name`
| One entry for each group the host will be associated with. 

The entry name is the group name.

|===


=== Ansible Inventory

The ansible inventory obtained from the pass database is built using the python
script located at link:../ansible/inventory/pass_inventory.py[../ansible/inventory/pass_inventory.py].

== Ansible Playbooks

Information on the available playbooks is available link:../ansible/playbook/passstore/README.adoc[here].
