= Tools
Snowdrop Team
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 3
:description: Auxiliary tools.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

[.lead]
Auxiliary tools for the `k8s_infra` project.

== passstore-vm-ssh.sh

Shell script that allows connecting to a host that’s added to the
passwordstore database.

=== Requirements

[arabic]
. pass installed on the computer (https://www.passwordstore.org/)
* Fedora:
+
[source,bash]
----
$ dnf install pass
----
* RHEL
+
[source,bash]
----
$ yum install pass
----
. team’s pass database updated on the computer
* check the project documentation

=== Usage

Call the script passing at least 2 of the 3 arguments.

.Connect to a passwordstore VM
[source,bash]
----
./tools/passstore-vm-ssh.sh <1> <2> <3> <4>
----
<1> Cloud provider.
<2> Inventory host name.
<3> Passwordstore database folder.
<4> SSH command to be executed on remote host.

.Script parameters
[%header,cols="2,4"]
|===
| Parameter | Description

| 1: `VM_PROVIDER`

[.fuchsia]#string# / [.red]#required# 
a| Cloud provider

Choices: 

* `openstack`

| 2: `VM_NAME`

[.fuchsia]#string# / [.red]#required# 
a| Name of the VM to connect to. 

This is the inventory name of the VM.

| 3: `PASSWORD_STORE_DIR`

[.fuchsia]#string#
a| Location of the PASSWORDSTORE database.

This parameter is optional if the `PASSWORD_STORE_DIR` environment 
 variable is set. If neither this parameter is defined nor the 
 `PASSWORD_STORE_DIR` env var is set the script will fail.


| 4: SSH COMMAND

[.fuchsia]#string#

a| Optional command to be executed on remote host. 

If none, the ssh connection is returned to the user.

|===

Connect to a remote host.

[source,bash]
----
./tools/passstore-vm-ssh.sh openstack vm20210221-t01 ~/git/passdatabase/
----

As output the script will print the `ssh` command to be executed and
also launch it. For instance, the output of the previous command would
be something like the following.

[source,bash]
----
### SSH COMMAND: ssh -i /home/johndoe/.ssh/vm20210221-t01 loginuser@xxx.xxx.xxx.xxx -p 22
[loginuser@h01-116 ~]
----

Execute a command on the remote host.

[source,bash]
----
./tooling/passstore-vm-ssh.sh hetzner h01-116 ~/github/snowdrop/pass/ ls
----

As output the script will print the `ssh` command to be executed and
also launch it. For instance, the output of the previous command would
be something like the following.

[source,bash]
----
### SSH COMMAND: ssh -i /home/johndoe/.ssh/vm20210221-t01 loginuser@xxx.xxx.xxx.xxx -p 22 ls
Documents
----

=== The passwordstore database

The script gathers from the passwordstore database the following
information for using on the connection.

* rsa secret key (id_rsa)
* host IP (ansible_ssh_host)
* ssh port (ansible_ssh_port)
* os user (os_user)

The RSA Secret Key contents are used to generate the ssh identity file
at `~/.ssh/`, if that file doesn’t already exist.
