= Kubernetes Ansible Playbooks
Snowdrop Team (Antonio Costa)
:icons: font
:revdate: {docdate}
:toc: left
:description: This document describes OpenStack specific playbooks.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Requirements

=== Environment variables

.Environment variables
[cols="2,5"]
|===
| Environment Variable | Description

| `VM_NAME`

[.fuchsia]#string#

[.red]#required# 

a| Name of the VM where the tools will be installed throughout the document

|===

=== Ansible Inventory

[WARNING]
====
Be sure that a host group entry exists for the version you
want to install within the `inventory/hosts` file

[source,yaml]
----
        k8s_121:
          vars:
            k8s_version: 1.21.4
            k8s_dashboard_version: v2.3.1
----
====

== Playbooks

=== Install a Kubernetes cluster using Passwordstore

Installs a new kubernetes cluster on an existing host using the team 
passwordstore as Ansible Inventory source.

To select which components are to be installed use the following ansible tags.

[width="100%",cols="25%m,10%c,65%",options="header",]
|===
| Tag | Always | Description

| containerd | icon:times[] | Installs link:https://containerd.io/[containerd] as CRI

| docker | icon:times[] | Installs Docker as CRI

| ingress | icon:times[] | Installs link:https://kubernetes.io/docs/concepts/services-networking/ingress/[Ingress]

| k8s_cluster | icon:check[] | Installs the Kubernetes cluster

| k8s_dashboard | icon:times[] | Installs the link:https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/[Kubernetes Dashboard]
|===

.Deploy kubernetes on a host installing docker and the Dashboard
[source,bash]
----
ansible-playbook ansible/playbook/kubernetes/k8s_install_passstore.yml -e vm_name=${VM_NAME} --tags docker,k8s_dashboard
----

=== Uninstall a Kubernetes cluster

To uninstall a kubernetes cluster (kubeadmin, kubelet, ..), execute this
playbook.

.Delete kubernetes cluster
[source,bash]
----
ansible-playbook ansible/playbook/kubernetes/k8s_remove.yml -e vm_name=${VM_NAME} 
----

== Other k8s tools

Several tools can be installed using the generic install tooks playbook. To deploy other k8s tools.

.Common parameters
[cols="2,5"]
|===
| Parameter | Description

| `vm_name`

[.fuchsia]#string#

[.red]#required# 

a| Name of the k8s host to apply the configuration

| `state`

[.fuchsia]#string#

[.red]#required# 

a| One of:

* `present`: Install
* `absent`: Uninstall

|===


=== k8s_cert_manager

[source,bash]
----
ansible-playbook ansible/playbook/kubernetes/k8s_install_tools.yml \
  -e vm_name=${VM_NAME} -e state=present \
  --tags k8s_cert_manager
----

As a result the following resources should be available.

[source]
----
$ kubectl -n cert-manager get all
NAME                                           READY   STATUS    RESTARTS   AGE
pod/cert-manager-7c869867bf-jlwxj              1/1     Running   0          88s
pod/cert-manager-cainjector-54c9d9b775-9zhrm   1/1     Running   0          88s
pod/cert-manager-webhook-7f7469bdb7-m5b5z      1/1     Running   0          88s
pod/godaddy-webhook-c6b5f74fd-5w7q6            1/1     Running   0          66s

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/cert-manager           ClusterIP   10.103.153.41   <none>        9402/TCP   88s
service/cert-manager-webhook   ClusterIP   10.111.63.241   <none>        443/TCP    88s
service/godaddy-webhook        ClusterIP   10.107.66.226   <none>        443/TCP    66s

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cert-manager              1/1     1            1           88s
deployment.apps/cert-manager-cainjector   1/1     1            1           88s
deployment.apps/cert-manager-webhook      1/1     1            1           88s
deployment.apps/godaddy-webhook           1/1     1            1           66s

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/cert-manager-7c869867bf              1         1         1       88s
replicaset.apps/cert-manager-cainjector-54c9d9b775   1         1         1       88s
replicaset.apps/cert-manager-webhook-7f7469bdb7      1         1         1       88s
replicaset.apps/godaddy-webhook-c6b5f74fd            1         1         1       66s
----


More information on the link:https://cert-manager.io/docs/installation/[cert-manager] web page.


=== k8s_issuer_certificate

[source,bash]
----
ansible-playbook ansible/playbook/kubernetes/k8s_install_tools.yml -e vm_name=${VM_NAME} -e letsencrypt_env=prod --tags k8s_issuer_certificate
----

.k8s_issuer_certificate parameters
[cols="2,5"]
|===
| Parameter | Description

| `api_key`

[.fuchsia]#string#

[.red]#required# 

a| GoDaddy API key.

| `api_secret`

[.fuchsia]#string#

[.red]#required# 

a| GoDaddy API secretkey.

| `letsencrypt_env`

[.fuchsia]#string#

a| Let's Encrypt environment to use.

* *`staging` <= Default:* Staging environment
* `prod`: Production environment

|===

[source,bash]
----
ansible-playbook ansible/playbook/kubernetes/k8s_install_tools.yml \
  -e vm_name=${VM_NAME} -e letsencrypt_env=prod \
  -e api_key=$(pass show godaddy/prod/api-key) -e api_secret=$(pass show godaddy/prod/secret-key) \
  -e state=present --tags k8s_issuer_certificate
----
